### ISSUE TITLE
ECR-001.소셜 회원가입/로그인 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#106]
**화면**
화면코드 = A001

![image](https://user-images.githubusercontent.com/54697115/74007340-73e31880-49c1-11ea-880a-413ca7d3cfe9.png)

**ASIS**
- 소셜 회원가입 프로세스가 변경된 현재 기획설정과 다름
- 해당 부분은 구두로 전달하겠습니다.

**TOBE**
- App 스토리보드 0.8의 15번 슬라이드의 "2.소셜 회원가입/로그인" 순서 참고
- 해당 부분은 구두로 전달하겠습니다.

**작성자**
- 전윤민

**재현과정**
- App실행 > A001에서 회원가입 Button Tap > 소셜(네이버,카카오,페이스북) 아이콘 Tap

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A000_04 ~ TC_A000_15

**Comment by kimbakcho** [comment]
하루

**Comment by kimbakcho** [comment]
해당 부분 수정 완료

**Comment by younbly** [comment]
1. Facebook → 로딩 후, 차후 이벤트 없음
2. kakao → 이미 가입 상태라, 소셜가입 프로세스 진행 불가(DB 초기화 후 진행)
3. Naver → 개발 중 상태라, 로그인 불가라는 메시지 뜸

**Comment by kimbakcho** [comment]
수정 완료
