### ISSUE TITLE
ECR-002. 로그인 버튼 활성/비활성 기능 미적용

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#107]
**화면**
- 화면코드 = A001

![image](https://user-images.githubusercontent.com/54697115/74007779-7e51e200-49c2-11ea-98b2-2245b68adcfe.png)

![image](https://user-images.githubusercontent.com/54697115/74007785-83169600-49c2-11ea-9b60-1d8454947103.png)

**ASIS**
- 디폴트 : 비활성 적용되어 있지 않은
- Button 활성에 따른 디자인 변화 없음

**TOBE**
- 디폴트 : 비활성화
- 활성화 조건 
   : 아이디 입력창에 1자 이상입력 & 패스워드 입력창에 8자 이상 입력

**작성자**
- 전윤민

**재현과정**
- A001에서 아이디, 패스워드에 데이터 입력 시, 변화관찰

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A001_06
- TC_A001_07
- TC_A001_08
- TC_A001_09

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료
