### ISSUE TITLE
ECR-003. 로그인 Button Tap 시 등장하는 Dialog 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#108]
**화면**
화면코드 = A001

![image](https://user-images.githubusercontent.com/54697115/74317134-2a7a3b00-4dbe-11ea-927d-527138d5e64a.png)

**ASIS**
- 로그인 Button Tap시, 등장하는 Dialog의 내용이 영문으로 작성되어 있음
- 로그인 Button Tap시, 등장하는 Dialog가 기획과 다음

**TOBE**
- Dialog의 Text 및 디자인 적용_(XD 디자인문서 참고)_
- 로그인 Button Tap시, 등장하는 Dialog를  아래를 참고하여 변경 (App스토리보드 0.8 버전 참고)

![image](https://user-images.githubusercontent.com/54697115/74317417-bab88000-4dbe-11ea-88bb-fe31f198f562.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0

**관련 테스트 케이스**
- TC_A001_10 ~ TC_A001_15

**Comment by kimbakcho** [comment]
현재는 구글이 로그인시 실패하는 이유를 던져줌. 
해당 내용 분석 후 지원하는 내용만 한글로 변환 뒤 Dialog 가능함 . 
4번 같은 경우는 분석이 필요함. 
소요기간 :  반나절 이내

**Comment by kimbakcho** [comment]
수정 완료

**Comment by younbly** [comment]
ASIS →아이디에  . 이 없을 때 2번 Dialog 등장
ex) ttfd15@navercom 입력 시, 2번 dialog 등장

TOBE → 아이디에  @ or  .(dot) 둘 중 하나라도 없으면 1번 dialog 등장

**Comment by younbly** [comment]
4번의 경우, 영문 메시지 표시 확인

**Comment by kimbakcho** [comment]
수정 완료

**Comment by younbly** [comment]
4번 영문메시지 제외, 오류 수정 확인

**Comment by younbly** [comment]
4번 영문메시지는 아래와 같습니다. 

A network error (such as timeout,  interrupted connection or unreachable host) has occurred
