### ISSUE TITLE
ECR-014. "모든 약관의 동의합니다" 체크 Button 개선

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#109]
**화면**
화면코드 = A002
![image](https://user-images.githubusercontent.com/54697115/74317919-9610d800-4dbf-11ea-892d-a38a1a5dc5f1.png)

**ASIS**
- 아래 5개의 체크버튼을 모두 체크했을 때, "모든 약관에 동의합니다" 가 체크되지 않음

    1) 서비스 이용 약관 동의
    2) 개인정보 수집 이용 동의
    3) 위치정보 활용 동의
    4) 마케팅 정보 메일 수신 동의(선택)
    5) 만 14세 이상입니다.

**TOBE**
- 아래 5개의 체크버튼을 모두 체크했을 때, "모든 약관에 동의합니다" 또한 체크상태로

    1) 서비스 이용 약관 동의
    2) 개인정보 수집 이용 동의
    3) 위치정보 활용 동의
    4) 마케팅 정보 메일 수신 동의(선택)
    5) 만 14세 이상입니다.

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A002_04

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료
