### ISSUE TITLE
ECR-004. 휴대폰인증에서 재요청 메시지 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#110]
**화면**
화면코드 = A004

![image](https://user-images.githubusercontent.com/54697115/74320694-6dd7a800-4dc4-11ea-8dd3-5249353ab636.png)

**ASIS → TOBE**

![image](https://user-images.githubusercontent.com/54697115/74319329-15071000-4dc2-11ea-894e-90065ca7e589.png)

1. 인증번호 재요청 메시지의 디폴트값이 0초로 되어 있음
    → 디폴트값으로 해당 메시지를 숨김처리
    → 인증번호를 요청하고 재요청시간이 카운트다운될 때만 등장

2. 인증번호 재요청 메시지를 디폴트값이 600초로 뒤에 전송할 수 있음
    → 120초로 변경

3. 인증번호 재요청 카운트다운이 시작 된 후, 1초에서 멈춤
    → 카운트다운이 완료 되면 *해당 메시지를 숨김 

          *인증번호는 0초 후에 다시 요청할 수 있습니다.

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A004_13

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
어뷰징 처리 및 해당 부분 처리 완료
