### ISSUE TITLE
ECR-005. 휴대폰인증 확인 Button 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#111]
**화면**
화면코드 = A004

![image](https://user-images.githubusercontent.com/54697115/74320858-b42d0700-4dc4-11ea-99df-d1228303e485.png)

**ASIS → TOBE**
1. 틀린 인증번호 입력 시 띄어지는 팝업(A004_01)을 닫으면 로딩이 종료되지 않음
   → 팝업(A004_01)을 닫으면 로딩이 종료되도록

**작성자**
- 전윤민

**재현과정**
- 틀린 인증번호 입력 > 팝업(A004_01) 닫음

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A004_11

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
해당 부분 수정 완료
