### ISSUE TITLE
ECR-006. 휴대폰인증 확인 Button 오류2

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#112]
**화면**
화면코드 = A004

![image](https://user-images.githubusercontent.com/54697115/74320858-b42d0700-4dc4-11ea-99df-d1228303e485.png)

**ASIS → TOBE**
1. Button의 디폴트 값 = 활성
     → Button의 디폴트 값 = 비활성
   
2. Button의 활성조건 미적용
     → 인증번호 입력창에 값이 입력되면 Button 활성화

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A004_08
- TC_A004_09

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료
