### ISSUE TITLE
ECR-007. 패스워드 확인입력창의 Placeholder 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#113]
**화면**
화면코드 = A005

![image](https://user-images.githubusercontent.com/54697115/74322199-ec354980-4dc6-11ea-8306-55fbfec7a398.png)

**ASIS → TOBE**
1.패스워드 확인의 Placeholder 메시지가 "비밀번호 입력"으로 되어 있음
    → Placeholder 메시지를 "비밀번호 확인"으로 변경

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A005_15

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료
