### ISSUE TITLE
ECR-008. 패스워드 조건 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#114]
**화면**
화면코드 = A005

![image](https://user-images.githubusercontent.com/54697115/74321755-2eaa5680-4dc6-11ea-9083-bf346c1d1c72.png)

**ASIS → TOBE**
1. 패스워드 조건이 8자입력으로 되어있음
    → 패스워드 조건을 아래와 같이 변경

![image](https://user-images.githubusercontent.com/54697115/74321930-73ce8880-4dc6-11ea-9a03-ef869e9da0cf.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A005_08 ~ 14

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료

**Comment by younbly** [comment]
아래 처리 미적용

1) 16자가 넘는 패스워드는 불허

**Comment by kimbakcho** [comment]
수정 완료
