### ISSUE TITLE
ECR-009. 생년월일 입력창에서 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#115]
**화면**
화면코드 = A006

![image](https://user-images.githubusercontent.com/54697115/74322416-40402e00-4dc7-11ea-8820-200650abf90b.png)

**ASIS → TOBE**
1. 최대년도 선택 제한 미적용(2020년까지 선택 가능)
      → 최소년도를 올해 기준으로 - 14 선택이 가능하도록

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A006_12~13

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료
