### ISSUE TITLE
ECR-011. 패스워드 찾기(이메일인증) 다음 Button 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#117]
**화면**
화면코드 = A011

![image](https://user-images.githubusercontent.com/54697115/74324384-51d70500-4dca-11ea-8d4c-25ec54ddde54.png)

**ASIS → TOBE**
1. 이메일 입력값이 이메일 형식일 경우에만 Button 활성화
    → 입력값이 있으면 Button 활성화
    → Button을 Tap했을 때, 이메일 형식이 아니면 아래 유효성 검사메시지 표시

![image](https://user-images.githubusercontent.com/54697115/74324071-cf4e4580-4dc9-11ea-903c-b8ed43aafac5.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A011_02

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료
