### ISSUE TITLE
ECR-012. 이메일에서 패스워드 변경 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#118]
**화면**
화면 = 패스워드 변경 이메일

![image](https://user-images.githubusercontent.com/54697115/74324878-11c45200-4dcb-11ea-8628-0190997a6205.png)

**ASIS → TOBE**
1. , 패스워드 조건이 App에서 기획과 다름(6자리로 설정가능)
    → 패스워드 조건을 아래와 같이 변경

![image](https://user-images.githubusercontent.com/54697115/74324720-c7db6c00-4dca-11ea-8662-d2ef7a57db0a.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_Ect_02

**Comment by kimbakcho** [comment]
해당 부분 분석 필요 분석 기간 대략 2~3일 정도

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/76411654-9491fa00-63d5-11ea-9085-94adb0583c4b.png)

수정 완료

**Comment by younbly** [comment]
ASIS = 8자 **이하면** "패스워드는 최소 8자 이상" 표시
TOBE = 8자 **미만이면** "패스워드는 최소 8자 이상" 표시

[추가설명] 8자를 입력하면, 사라져야할 "패스워드는 최소 8자 이상"가 계속 표시됨

**Comment by younbly** [comment]
모바일에서는 아래처럼 화면이 압축되서 보이는데, 별도 제작해야하는 것인지 문의드립니다.

![image](https://user-images.githubusercontent.com/54697115/76427484-b4361c00-63ef-11ea-8d96-529a0e29f384.png)

**Comment by kimbakcho** [comment]
해당 부분 수정 완료
