### ISSUE TITLE
ECR-015. 패스워드 변경 후, 이동경로 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#120]
**화면**
화면코드 = A010, A010_01

![image](https://user-images.githubusercontent.com/54697115/74326659-1fc7a200-4dce-11ea-9ef9-5bc9ff6e5aad.png)

![image](https://user-images.githubusercontent.com/54697115/74326697-3241db80-4dce-11ea-814e-d81b70cae00a.png)

**ASIS → TOBE**
1. 팝업(A010_01)에서 확인 Button을 누르면 비로그인 상태에 B001로 이동
    → 확인 Button을 누르면 로그인 화면(A001)로 이동

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A010_14

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료
