### ISSUE TITLE
ECR-016. A003 헤더명 변경오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#121]
**화면**
화면코드 = A003

![image](https://user-images.githubusercontent.com/54697115/74765344-b9a7b700-52c6-11ea-8dfb-d2f42b430d7b.png)

**ASIS → TOBE**
1. A003에서 헤더명이 약관 및 정책에따라 변경되지 않고 "서비스 이용약관"으로 고정됨
    → 헤더명이 선택한 약관 및 정책에따라 변경

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 파이
- App버전 = 1.0 

**관련 테스트 케이스**
- TC_A010_14

**Comment by kimbakcho** [comment]
반나절 이내

**Comment by kimbakcho** [comment]
수정 완료
