### ISSUE TITLE
[배포 후 테스트][FE-002]

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#123]
**작성사유**
- 페이스북 로그인API 실행Fail

**참고화면**
- 화면코드 = J001
![image](https://user-images.githubusercontent.com/54697115/81965080-8325d200-9652-11ea-9927-45400006c18c.png)

**화면재현**
- Step1. J001 진입
- Step2. 페이스북 ID 로그인
- Step3. 페이스북 Button Tap

**ASIS → TOBE**
- ASIT = 페이스북 소셜api 실행 시, 에러메시지 등장

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8

**Comment by kimbakcho** [comment]
페이스북 개발자 모드로 안된것으로 확인됨

**Comment by younbly** [comment]
@kimbakcho 개발자모드 해제 시, 테스트를 다시 진행하겠습니다.
