### ISSUE TITLE
[베타이후 진행][FE-008]

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#132]
**작성사유**
- 유효성검사 제거 요청

**화면**
- 화면코드 = J004
![image](https://user-images.githubusercontent.com/54697115/81969582-2843a900-9659-11ea-88d1-589f60635065.png)

**화면재현**
- Step1. J004 진입
- Step2. 휴대폰 input-field 탭
- Step3. 2~4자 입력

**ASIS → TOBE**
- ASIT = 유효성검사 존재
- TOBE = 유효성검사 제거

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8

**Comment by kimbakcho** [comment]
유효성 검사 기능 제거 다시 검토 필요

**Comment by younbly** [comment]
회의 때, 논의 진행 하겠습니다.
