### ISSUE TITLE
[FE-010]_인증번호 쿨타임 표시 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#135]
**작성사유**
- 120초가 지난 후, 시간 표시값이 리셋 되지 않음(계속 0초에서 머뭄)

**화면**
- 화면코드 = J004
![image](https://user-images.githubusercontent.com/54697115/82144178-9cf92c00-9881-11ea-9920-401250bf186c.png)

**화면재현**
- Step1. J004진입
- Step2. 인증번호 요청
- Step3. 120초 지남

**ASIS → TOBE**
- ASIT = 0초에서 변화 없음
- TOBE = 0초가 되는 즉시 시간 값을 120초 변경

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정 확인 1.8.7
