### ISSUE TITLE
[미해결][IMP_001]_가입시, 아이디 입력창 및 유효성검사 메시지 개선

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#137]
**화면**
- 화면코드 = J006
![image](https://user-images.githubusercontent.com/54697115/82149042-eef57e00-9890-11ea-9a3e-13cc903d7b78.png)

**ASIS → TOBE**
① 아이디 입력창 변경
- ASIS = 아이디 입력창
- TOBE = 아이디 입력창 + 이메일 Dropdown list
- 사유 = 이메일을 작성하는 것보다, 선택하게 하는 것이 유저편의성 측면에서 이로움 

② 유효성메시지 숨김
- ASIS = 유효성메시지 등장 후, 적절한 값으로 수정해도 유효성메시지가 사라지지 않음
- TOBE = 적정 값을 입력하면, 유효성메시지가 사라지도록 처리
- 사유 = 값을 적절하게 수정했음에도, 계속 유효성메시지가 표시되면 값이 여전히 적절하지 않다고 오해를 줄 여지가 있음

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by younbly** [comment]
재 테스트

**Comment by kimbakcho** [comment]
1.8.8
수정
