### ISSUE TITLE
[FE-015]_닉네임 및 자기소개 글자수 제한 변경

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#141]
**작성사유**
- 닉네임 및 자기소개 글자수 제한 수정필요

**화면**
- 화면코드 = J007
![image](https://user-images.githubusercontent.com/54697115/82151357-24e93100-9896-11ea-9fd5-b4b987e83db1.png)

**화면재현**
- Step1. J007진입

**ASIS → TOBE**
①닉네임 글자수 제한
- ASIS = 80자 제한
- TOBE = 20자 제한

②자기소개 글자수 제한
- ASIS = 80자 제한
- TOBE = 100자 제한

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정 확인 1.8.7
