### ISSUE TITLE
[FE-016]_키패드 타입 수정 필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#142]
**작성사유**
- 키패드 타입 수정 필요

**화면**
- 화면코드 = J009
![image](https://user-images.githubusercontent.com/54697115/82152482-6da3e880-989c-11ea-8718-d23896697924.png)

**화면재현**
- Step1. J009진입
- Step2. 아이디 입력창 Tap

**ASIS → TOBE**
- ASIS = 일반 키패드 등장
- TOBE = 이메일 키패드 등장

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
