### ISSUE TITLE
[해결불가][FE-017]_자동입력 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#143]
**작성사유**
- 입력하지 않은 값이 자동으로 입력됨

**화면**
- 화면코드 = J009
![image](https://user-images.githubusercontent.com/54697115/82152759-70074200-989e-11ea-8973-59ec9a8625cb.png)

**화면재현**
첫번째 방법
- Step1. J009진입
- Step2. 아이디 입력창에 가입된 아이디 입력
- Step3. 다음 Button 눌러 J010진입
- Step4. Back button을 눌러 J009로 복귀
- Step5. @ 이후 값을 삭제
- Step6. @ 뒤에 아무 값이나 입력

두번째 방법
- Step1. J009진입
- Step2. 아이디 입력창에 가입되지 않은 아이디 입력
- Step3. 다음 Button 눌러
- Step4. 유효성메시지 등장
- Step5. @ 이후 값을 삭제
- Step6. @ 뒤에 아무 값이나 입력

**ASIS → TOBE**
- ASIS = 입력 값 앞에 "@ 뒤에 앞에 값"이 자동으로 입력됨
- TOBE = 입력 값만 입력되도록

**참고사항**
- J009뿐만 아니라 이메일을 입력하는 다른 J006, J012에서도 관측됨

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
해당 부분 어플리케이션 에서 입력하는것이 아닌 키보드에서 자동 입력 되는것으로 확인됨 .
