### ISSUE TITLE
[FE-018]_키패드 타입 수정 필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#144]
**작성사유**
- 키패드 타입 수정 필요

**화면**
- 화면코드 = J010
![image](https://user-images.githubusercontent.com/54697115/82152864-210ddc80-989f-11ea-93ef-41f57312ac96.png)

**화면재현**
- Step1. J010진입
- Step2. 인증번호입력창 Tap

**ASIS → TOBE**
- ASIS = 일반 키패드 등장
- TOBE = 숫자 키패드 등장

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
