### ISSUE TITLE
[FE-019]_인증번호 요청 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#145]
**작성사유**
- 인증번호 요청 에러화면

**화면**
- 화면코드 = J010
![image](https://user-images.githubusercontent.com/54697115/82152914-603c2d80-989f-11ea-893f-0c31e536587b.png)

**화면재현**
- Step1. J010진입
- Step2. 맞는 휴대폰번호 입력하고 인증번호 요청
- Step3. 120초 지나기 전 뒤로가기 Button 탭
- Step4. 맞는 휴대폰번호 입력하고 인증번호 재요청

**ASIS → TOBE**
- ASIS = 회색화면 등장
- TOBE = 인증번호 요청 불가(회원가입 단 처럼)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
테스트 재시도 필요

**Comment by younbly** [comment]
재현 시, 이상없음 확인(1.8.7)
