### ISSUE TITLE
[IMP_002]_인증번호 덮어쓰기

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#146]
**화면**
- 화면코드 = J010
![image](https://user-images.githubusercontent.com/54697115/82153222-22d89f80-98a1-11ea-8cb5-b13088996c85.png)

**ASIS → TOBE**
- ASIS = 인증번호 재요청 시, 이전 값이 그대로 남아있음
- TOBE = 인증번호 재요청 시, 이전 값을 지우고 새로 받은 값으로 덮어씌움
- 사유 = 유저 편의성

**참고사항**
- J006(회원가입)에서는 인증번호 재요청 시, 이전 값을 지우고 새로 받은 값으로 덮어씌움

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
120 초 지난뒤 재요청시 이전값 삭제됨 .

**Comment by younbly** [comment]
수정확인 (1.8.7)
