### ISSUE TITLE
[IMP_003]_페이징 처리 개선

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#149]
**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/82212446-8cae8300-994d-11ea-81c6-d8f72ebde442.png)

**ASIS → TOBE**
- ASIS = Ball 추가 로드(Paging) 후, 어떤 Action도 없어 Ball 추가 로드되었다는 점을 알기 어려움
- TOBE =Ball 추가 로드(Paging) 후, Ball이 추가 로드되었다는 점을 알리기 위해 화면의 반 정도 Scroll down(논의필요)
- 사유 = 유저 편의성

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by younbly** [comment]
진행요청 바람

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
