### ISSUE TITLE
퀘스트  큐브 Inner Page2

### ISSUE THREAD

**Issue by kimbakcho** [kimbakcho/forutonafront#15]
![image](https://user-images.githubusercontent.com/13299104/68576434-706aee80-04b1-11ea-9344-c8f1886b74b8.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/68690310-266b3100-05b5-11ea-961e-9df48eab7014.png)
![image](https://user-images.githubusercontent.com/13299104/68690328-2ec36c00-05b5-11ea-92bd-6d6805bd3106.png)

외부 오픈 소스 에디터 내제화 완료및 해당 페이지 완료

**Comment by younbly** [comment]
우왕 굿!
