### ISSUE TITLE
[진행대기][DE-006]_H004 부적절한 헤더위치

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#151]
**작성사유**
- H004 부적절한 헤더위치

**화면**
- 화면코드 = H004
![image](https://user-images.githubusercontent.com/54697115/82213463-2296dd80-994f-11ea-9904-242e3de6b3bc.png)

**화면재현**
- Step1. H004 진입
- Step2. 검색어 입력
- Step3. 검색 Button 탭

**ASIS → TOBE**
- ASIS = 부적절한 헤더 위치
- TOBE = 헤더위치 적정값을 수정

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
새 버전 업데이트시 재 테스트 필요
![image](https://user-images.githubusercontent.com/13299104/82221061-73600380-995a-11ea-8f55-ed9d44aa7572.png)

**Comment by younbly** [comment]
1.8.3 수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
