### ISSUE TITLE
[TOBE 수정예정][FE-022]_GPS off 예외처리

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#152]
**작성사유**
- GPS off 예외처리

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/82214863-6f7bb380-9951-11ea-9189-1bb0fb1c9634.png)

**화면재현**
- Step1. GPS off
- Step2. App 실행하여 H001 진입

**ASIS → TOBE**
- ASIS = 로딩 중에서 변화 없음
- TOBE = GPS off일 경우, wifi 또는 기지국으로 잡은 위치를 중심위치로 설정**(개발단 논의 필요)**

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
위치 정보 OFF 될 경우 wifi,기지국으로 잡을수가 없음 핸드폰에서 위치 정보를 on Off 하는것이 
GPS on off와는 다른 개념 으로 인지됨 
위치 정보를 켜면 wifi,GPS,기지국 3가지 종합하여 가장 최적의 값을 파악함 
아래와 같이 핸드폰 설정이 되어 있음

![image](https://user-images.githubusercontent.com/13299104/82220600-d1401b80-9959-11ea-9fae-e58cb5935a13.png)

**Comment by kimbakcho** [comment]
대안으로 앱 실행시 위치 정보가 꺼져있을때 켤지 물어 본후  만약 위치 정보 ON 하면 로딩함.

**Comment by younbly** [comment]
GPS 오프 시, GPS On을 요구하는 메시지 표시

**Comment by kimbakcho** [comment]
1.8.4
GPS 오프 시 on 요청 거절시 신도림역 을 초기값으로 가지며 자신과의 거리는 표시 인함

**Comment by younbly** [comment]
수정내역 확인 
회의 때, 상세히 공유 요청

**Comment by younbly** [comment]
1. Last 위치를 디폴트로 지정
2. 데이터가 없으면 '신도림역'
