### ISSUE TITLE
[IMP_004]_Tag에 Tap이벤트 추가

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#154]
**화면**
- 화면코드 = H001 / H006
![image](https://user-images.githubusercontent.com/54697115/82281659-dd18f580-99cc-11ea-8470-5357a75902ae.png)

**ASIS → TOBE**
- ASIS = 표시된 영역에 Tap이벤트 없음
- TOBE = Tap하면 해당 태그 검색어로 검색하는 이벤트 추가

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.3 수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
