### ISSUE TITLE
[FE-024]_수치표시 방식 수정요청

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#155]
**작성사유**
- 수치표시 방식이 기획과 다르게 적용됨

**화면**
- 화면코드 = H001 / H006
![image](https://user-images.githubusercontent.com/54697115/82281944-9c6dac00-99cd-11ea-8fe0-dd65d599ed48.png)

**화면재현**
- Step1. H001 진입
- Step2. 태그에서 역삼각형 버튼 탭

**ASIS → TOBE**
- ASIS = 수치값의 크기에 따라 분기 처리되지 않고 단지 'k(1000)' 단위로 표시됨
- TOBE = 아래 참고사항을 참고하여 수치값의 수치에 따라 분기처리하여 표시

**참고사항**
- [참고자료]_수치 표시 방식_v0.1에서 발췌
![image](https://user-images.githubusercontent.com/54697115/82282093-fa9a8f00-99cd-11ea-94ee-f210737e27f8.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
