### ISSUE TITLE
[DE-007]_접기버튼 숨김

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#156]
**작성사유**
- 접기버튼 숨김 처리

**화면**
- 화면코드 = H006
![image](https://user-images.githubusercontent.com/54697115/82283164-84e3f280-99d0-11ea-9de1-9c1d135d681a.png)

**ASIS → TOBE**
- ASIS = 펼쳤을 때 역삼각형 Butto 표시
- TOBE = 펼쳤을 때 역삼각형 Butto 숨김

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.3 수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
