### ISSUE TITLE
[FE-025]_참여한 Ball 표시되지 않음

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#158]
**작성사유**
- 참여한 Ball 표시되지 않음

**화면**
- 화면코드 = H003
![image](https://user-images.githubusercontent.com/54697115/82355323-040f1000-9a3d-11ea-83a1-c66cf5c57bb1.png)

**화면재현**
- Step1. 다른 Ball 댓글 or Ball 평가를 진행
- Step2. H003진입

**ASIS → TOBE**
- ASIS = 참여한 Ball이 표시되지 않음
- TOBE = 아래 참고사항을 참고하여 참여한 Ball은 H003에 표시

**참고사항**
- "[스토리보드]_포루투나App 리뉴얼_v0.7(미배포)"에서 발췌
![image](https://user-images.githubusercontent.com/54697115/82355406-20ab4800-9a3d-11ea-98f8-49dd2a7dc92b.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
일단 보면 참여로 프로그램 적용해둠 추후 해당 부분 적용 논의

**Comment by younbly** [comment]
표시기준 및 정렬기준에 대한 논의 필요
금주 회의 때 진행예정

**Comment by younbly** [comment]
데이터 호출 기준 = 유저가 View했던 Ball
