### ISSUE TITLE
[FE-026]_H003/H003_1에 Empty message 미적용

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#159]
**작성사유**
- H003/H003_1에 Empty message 미적용

**화면**
- 화면코드 = H003 / H003_1
![image](https://user-images.githubusercontent.com/54697115/82356013-fb6b0980-9a3d-11ea-886b-2f319fec9dd7.png)

**화면재현**
- Step1. 신규계정을 생성 (제작 및 참여한 Ball이 없도록)
- Step2. H003 or H003_1 집입

**ASIS → TOBE**
- ASIS = Empty message 미적용
- TOBE = 아래 참고사항을 참고하여 Empty message 적용

**참고사항**
- "[디자인_v0.6][스토리보드]_포루투나App 메뉴리뉴얼_v0.4"에서 발췌
![image](https://user-images.githubusercontent.com/54697115/82355963-e9896680-9a3d-11ea-8190-1ec2b278d964.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
적용

**Comment by younbly** [comment]
수정확인 (1.8.7)
