### ISSUE TITLE
[FE-027]_지우기 Button 기능 수정 요청

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#160]
**작성사유**
- 지우기 Button 기능 수정 요청

**화면**
- 화면코드 = H004 / H005 / H005_1 / H008
![image](https://user-images.githubusercontent.com/54697115/82356852-26a22880-9a3f-11ea-9c26-ffb2ae83e3b4.png)

**화면재현**
- Step1. H004 진입(또는 H005, H005_1, H008)

**ASIS → TOBE**
- ASIS =
    1) 디폴트 = 비활성화
    2) 활성화 조건 = 검색창에 값 입력

- TOBE 
    1) 디폴트 = Button 숨김
    2) 등장 조건 = 검색창에 값 입력

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
적용

**Comment by younbly** [comment]
수정확인 (1.8.7)
