### ISSUE TITLE
[논의필요][FE-028]_검색창에 검색어 표시 제한

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#161]
**작성사유**
- 아래 화면과 같은 상황을 만들지 않기 위한 대처 필요
![image](https://user-images.githubusercontent.com/54697115/82357279-da0b1d00-9a3f-11ea-8655-96b7b49cb8e9.png)

**화면**
- 화면코드 = H004 / H005 / H005_1 / H008
![image](https://user-images.githubusercontent.com/54697115/82356852-26a22880-9a3f-11ea-9c26-ffb2ae83e3b4.png)

**화면재현**
- Step1. H004 진입(또는 H005, H005_1, H008)

**ASIS → TOBE**
- ASIS = X button 뒤로 검색어 표시
- TOBE = X button 이전까지만 입력된 검색어 표시(논의필요)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인(1.8.7)
