### ISSUE TITLE
[IMP_005]_내가 참여한 Ball의 출력조건에 예외처리 추가

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#163]
**화면**
- 화면코드 = H003
![image](https://user-images.githubusercontent.com/54697115/82357863-aaa8e000-9a40-11ea-842f-8a343cb1dec3.png)

**ASIS → TOBE**
- ASIS = 내가 참여한 Ball 모두 표시
- TOBE = "내가 제작하지 않은 Ball" 중에서 내가 참여한 Ball 모두 표시 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.8 수정 
서버에서는 처리하지 않고 클라이언트에서 처리 
이미 서버에 저장된것은 추후 배포 이전에 삭제

**Comment by younbly** [comment]
수정확인
