### ISSUE TITLE
[FE-029]_GPS off 상태일 때, 검색예외처리 추가

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#164]
**작성사유**
- GPS off 상태일 때, 검색예외처리 추가

**화면**
- 화면코드 = H004 
![image](https://user-images.githubusercontent.com/54697115/82358180-1db25680-9a41-11ea-8871-7db4c17867a0.png)

**화면재현**
- Step1. H004 진입
- Step2. GPS off
- Step3. 검색어 입력
- Step4. 검색 Button 탭

**ASIS → TOBE**
- ASIS = 검색이 실행되나, 검색결과 없음
- TOBE = GPS On을 요구 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
적용

**Comment by kimbakcho** [comment]
1.8.8 적용

**Comment by younbly** [comment]
수정확인
