### ISSUE TITLE
[DE-010]_검색결과가 없을 경우 화면디자인 

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#165]
**작성사유**
- 검색결과가 없을 경우, 화면에 대한 대응 필요

**화면**
- 화면코드 = H005 / H005_1
![image](https://user-images.githubusercontent.com/54697115/82358830-0889f780-9a42-11ea-836a-4bbf851a0fda.png)

**화면재현**
- Step1. H005 진입(또는 H005_1 )

**ASIS → TOBE**
- TOBE = 1)Dropdown list 숨기고, 2)아래 Empty message표시

"검색 결과가 없습니다"

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
