### ISSUE TITLE
[FE-030]_지도에서 검색결과가 없을 경우 이벤트 예외처리 추가

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#166]
**작성사유**
- 지도에서 검색결과가 없을 경우 이벤트 예외처리 추가

**화면**
- 화면코드 = H008
![image](https://user-images.githubusercontent.com/54697115/82359510-f0ff3e80-9a42-11ea-91f3-384ddd1bd6f7.png)

**화면재현**
- Step1. H001 진입
- Step2. 중심위치 Tap
- Step3. H008 진입
- Step4. 검색창에 "검색결과가 없을 것 같은 값" 입력
- Step5. 검색 Button 탭

**ASIS → TOBE**
- ASIS = 이벤트 없음
- TOBE = 아래 Toast message 띄움

"검색결과가 없습니다"

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.3 수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
