### ISSUE TITLE
[논의필요][IMP_006]_GPS off 상태에서 I001 체크

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#168]
**화면**
- 화면코드 = I001
![image](https://user-images.githubusercontent.com/54697115/82578397-4c5a3980-9bc7-11ea-9073-399d9d0815d9.png)

**화면재현**
- Step 1. Gps off
- Step 2. I001 진입

**ASIS → TOBE**
- ASIS = 남산공원에 위치
- TOBE = (논의필요)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.4
현재 위치 정보 없을때 기본으로 신도림역을 보게 해놈 추후 쉽게 초기 Map 위치 변경 가능
