### ISSUE TITLE
퀘스트 큐브 Range 설정 뷰 

### ISSUE THREAD

**Issue by kimbakcho** [kimbakcho/forutonafront#17]
![image](https://user-images.githubusercontent.com/13299104/68576612-bf188880-04b1-11ea-8848-6c9e52791214.png)

**Comment by younbly** [comment]
"퀘스트 큐브 Range 설정"는 도입하지 않을 예정입니다. 개발 목록에서 삭제 요청드립니다.

**Comment by kimbakcho** [comment]
클로즈 합니다.
