### ISSUE TITLE
[IMP_007]_GPS off 상태에서, 재검색

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#170]
**화면**
- 화면코드 = I001
![image](https://user-images.githubusercontent.com/54697115/82581048-ea9bce80-9bca-11ea-97af-4ba05e2d5ebe.png)

**화면재현**
- Step 1. Gps off
- Step 2. I001 진입
- Step 3. 재검색 Button 탭

**ASIS → TOBE**
- ASIS = Ball 검색 실행X
- TOBE = Ball 검색 실행

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.4
수정 하지만 위치 정보  off시 자신과의 거리 부분은 일단  표시 안함

**Comment by younbly** [comment]
넵! 해당 Ball에서는 자신과의 거리는 표시하지 않아도 됩니다!

**Comment by younbly** [comment]
수정확인 (1.8.7)
