### ISSUE TITLE
[FE-032]_I001에서 Ball 검색 범위 이슈

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#171]
**작성사유**
- I001에서 Ball 검색 범위 체크 필요

**화면**
- 화면코드 = I001
![image](https://user-images.githubusercontent.com/54697115/82579515-e2db2a80-9bc8-11ea-9d05-759e5189009c.png)

**화면재현**
- Step1. I001 진입
- Step2. 고양시 가좌동 부근 검색

**ASIS → TOBE**
- ASIS = 지도검색범위에 이상발견(중앙 근처에 있는 Ball 검색이 되지 않음)
- TOBE = 아래 범위(파란색)만큼 검색범위를 설정
![image](https://user-images.githubusercontent.com/54697115/82579607-030ae980-9bc9-11ea-8e33-a28538b1700b.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
