### ISSUE TITLE
[FE_033]_GPS off 상태, 중심위치 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#172]
**작성사유**
- GPS off 상태일 때, I001의 중심위치값이 변경되지 않음

**화면**
- 화면코드 = I001 
![image](https://user-images.githubusercontent.com/54697115/82580299-f1761180-9bc9-11ea-810b-2f7fe5cf5a3c.png)

**화면재현**
- Step1. GPS off
- Step2. App실행
- Step3. I001 진입
- Step4. 지도 이동

**ASIS → TOBE**
- ASIS = '주소 없음'이라 표시
- TOBE = 지도의 중앙위치의 주소를 반영 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.4
수정 하지만 위치 정보  off시 자신과의 거리 부분은 일단  표시 안함

**Comment by younbly** [comment]
수정확인 (1.8.7)
