### ISSUE TITLE
[IMP_009]_Sub-navi의 Swipe 변경속도 이슈

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#175]
**화면**
- 화면코드 = G001/G002
![image](https://user-images.githubusercontent.com/54697115/82744856-eb925300-9db8-11ea-8287-126d5ddc20b5.png)

**화면재현**
- Step 1. G001
- Step 2. Swipe Action

**ASIS → TOBE**
- ASIS = Swipe시, Sub menu변화가 (페이지 변경속도보다) 느림
- TOBE =Swipe시, Sub menu변화속도를 페이지 변경속도와 동기화

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.8
속도 수정

**Comment by younbly** [comment]
수정확인
