### ISSUE TITLE
[FE_034]_페르소나 > Sub 메뉴 선택상태 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#176]
**작성사유**
- 특정 동작 이후, Sub 메뉴 선택상태에 오류가 있음

**화면**
- 화면코드 = G001
![image](https://user-images.githubusercontent.com/54697115/82745299-bccaab80-9dbd-11ea-870a-e9e491881dd8.png)

**화면재현**
- Step1. G001 진입
- Step2. Swipe 또는 Tap하여 G002로 이동 
- Step3. Setting Button Tap
- Step4. Back button Tap

**ASIS → TOBE**
- ASIS = 아래 화면 처럼 G002에서 Sub메뉴가 Profile버튼 선택상태
- TOBE = 페이지에 맞는 Sub메유 선택상태로
![image](https://user-images.githubusercontent.com/54697115/82745309-d10ea880-9dbd-11ea-876c-9d6014d496d7.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
