### ISSUE TITLE
[FE_037]_계정정보 수정 시, 닉네임 Validation 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#178]
**작성사유**
- 계정정보 수정 시, 닉네임 Validation 누락

**화면**
- 화면코드 = G010 / G001
![image](https://user-images.githubusercontent.com/54697115/82752013-3aaaa900-9df6-11ea-8b54-4804c68c5aa3.png)

**화면재현**
- Step1. G010 진입
- Step2. 닉네임을 'ㅇ' 로 입력
- Step3. 완료 Button Tap

**ASIS → TOBE**
- ASIS = 닉네임이 변경됨
- TOBE = 닉네임이 2자 미만이면, 아래 Validation 적용

"닉네임은 최소 2글자 이상이어야 합니다"

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.84 수정

**Comment by younbly** [comment]
'ㅇㅇ' 또는 '에헤'를 입력했을 때도 닉네임이 수정되지 않습니다.

세글자를 입력했을 때 수정되는 것으로 보아, 닉네임 최소값이 3글자로 설정되어 있는 것으로 보입니다.

**Comment by kimbakcho** [comment]
1.8.8
수정

**Comment by younbly** [comment]
수정확인
