### ISSUE TITLE
[FE_038]_계정정보 수정 시, 닉네임 Validation 메시지 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#179]
**작성사유**
- 계정정보 수정 시, 닉네임 Validation 메시지 수정 필요

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/82752085-a0973080-9df6-11ea-9df4-239b9526be0d.png)

**화면재현**
- Step1. G010 진입
- Step2. 닉네임에 특수문자 입력
- Step3. 완료 Button Tap

**ASIS → TOBE**
- ASIS = 첨부한 화면과 같음
- TOBE = Validation 메시지를 아래 처럼 수정

"띄어쓰기와 특수문자는 닉네임에 사용할 수 없습니다."

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
