### ISSUE TITLE
[FE_039]_계정정보 수정 시, 닉네임 중복체크 Validation 메시지 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#180]
**작성사유**
- 계정정보 수정 시, 닉네임 중복체크 Validation 메시지 수정

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/82752085-a0973080-9df6-11ea-9df4-239b9526be0d.png)

**화면재현**
- Step1. G010 진입
- Step2. 닉네임을 이미 존재하는 닉네임 입력
- Step3. 완료 Button Tap

**ASIS → TOBE**
- ASIS = 첨부한 화면과 같음
- TOBE = 이미 존재하는 닉네임이이면, 아래 Validation 메시지 표시

"이미 있는 닉네임입니다"

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
