### ISSUE TITLE
[FE_040]_계정정보 수정 시, ①닉네임 입력값 제한 및 ②최대값 표시

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#181]
**작성사유**
- 계정정보 수정 시, ①닉네임 입력값 제한 및 ②최대값 표시

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/82752242-99bced80-9df7-11ea-8346-8c5532cf4a05.png)

**화면재현**
- Step1. G010 진입
- Step2. 닉네임 입력창에 Focus

**ASIS → TOBE**
1. 닉네임 입력창에 최대 Char 입력제한
- ASIS = 80자 까지 입력 가능
- TOBE = 20자 까지 입력 가능

2. 최대 입력가능한 숫자 표시
- ASIS = 80 표시
- TOBE = 20 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4  수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
