### ISSUE TITLE
[FE_041]_프로필 이미지 수정 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#182]
**작성사유**
- "카메라","갤러리"로 프로필 이미지 수정 시, 에러 발생

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/82752470-4350ae80-9df9-11ea-8155-4d7462889256.png)

**화면재현**
방법1
- Step1. G010 진입
- Step2. 프로필 이미지 Tap
- Step3. 카메라를 선택
- Step4. 사진촬영을 하지 않고, G10로 이동

방법2
- Step1. G010 진입
- Step2. 프로필 이미지 Tap
- Step3. 갤러리를 선택
- Step4. 갤러리에서 이미지를 선택하지 않고, G10로 이동

**ASIS → TOBE**
- ASIS = 첨부화면과 같이 회색 이미지 표시
- TOBE = 이전 저장된 이미지 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4 수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
