### ISSUE TITLE
[IMP_011]_이미지 modal에서 취소Button을 Tap하면, Focus 실행무시

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#183]
**작성사유**
- 이미지 modal에서 취소Button을 Tap하면, Focus 실행무시

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/82752652-6f206400-9dfa-11ea-9d76-68183e093d07.png)

**화면재현**
- Step1. G010 진입
- Step2. 닉네임 or 자기소개 Focus
- Step3. 뒤로가기 눌러 키패드 내림
- Step4. 프로필 이미지 Tap
- Step5. 취소 Button을 눌러 Modal 내림

**ASIS → TOBE**
- ASIS = 닉네임 or 자기소개가 Focus되어 1)스크롤 이동 및 2)키패드 등장
- TOBE = 닉네임 or 자기소개가 Focus되어도 1)스크롤 이동 및 2)키패드 등장 없음

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
