### ISSUE TITLE
[FE_042]_프로필 "국가"정보 수정 시, 에러 발생

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#184]
**작성사유**
- "프로필 "국가"정보 수정 시, 에러 발생

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/82752737-1c937780-9dfb-11ea-81b2-223af0e620ae.png)

**화면재현**
- Step1. G010 진입
- Step2. 국가 Tap
- Step3. 국가를 변경하지 않고 뒤로가기 Tap

**ASIS → TOBE**
- ASIS = 3번째 화면 처럼 회색 바탕의 화면 표시
- TOBE = 국가를 변경하지 않고 G10으로 이동

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4 수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
