### ISSUE TITLE
[FE_043]_프로필 "국가"정보 수정 시, 에러 발생2

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#185]
**작성사유**
- "프로필 "국가"정보 수정 시, 에러 발생

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/82752794-8744b300-9dfb-11ea-9c29-15403877f5f5.png)

**화면재현**
- Step1. G010 진입
- Step2. 데이터 로딩 상태에서 국가 Tap

**ASIS → TOBE**
- ASIS = 2번째 화면처럼 회색 화면 표시
- TOBE = (논의필요) 로딩중 Tap 이벤트 불가하도록 조치

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
수정
1.8.4

**Comment by younbly** [comment]
수정확인 (1.8.7)
