### ISSUE TITLE
 [DE_012]_텍스트에서 줄바꿈 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#189]
**작성사유**
- 텍스트에서 줄바꿈 누락

**화면**
- 화면코드 = G012
![image](https://user-images.githubusercontent.com/54697115/82759192-aad12300-9e26-11ea-9e34-f3e4712e0b18.png)

**화면재현**
- Step1. G012 진입

**ASIS → TOBE**
- ASIS = * 앞에 줄바꿈 누락
- TOBE = * 앞에  줄바꿈 추가

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
