### ISSUE TITLE
QM002. 퀘스트 큐브 만들기 Step1. 퀘스트 설명

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#19]
![image](https://user-images.githubusercontent.com/54697115/68781470-30576780-067b-11ea-9a9b-3a6c9b12b063.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/68958229-0d5dbc80-080f-11ea-922f-87cf53bb000e.png)

![image](https://user-images.githubusercontent.com/13299104/68958317-35e5b680-080f-11ea-9e76-c258a4355d02.png)


해당 부분 완료
