### ISSUE TITLE
 [FE_045]_패스워드 수정 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#190]
**작성사유**
- 패스워드 수정 에러 = 완료Button Tap했을 때 이벤트 없음

**화면**
- 화면코드 = G012
![image](https://user-images.githubusercontent.com/54697115/82759303-7f9b0380-9e27-11ea-8ca1-ca526be22fc0.png)

**화면재현**
- Step1. G012 진입
- Step2. 1)현재 패스워드, 2)새 패스워드, 3)새 패스워드 확인 입력 (모두 맞는 값 입력)
- Step3. 완료 Button tap

**ASIS → TOBE**
- ASIS = 이벤트 없음
- TOBE = 패스워드 수정

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
