### ISSUE TITLE
[DE_014]_헤더 텍스트 및 Status bar 색상변경

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#192]
**작성사유**
- 어색한 헤더 텍스트 변경

**화면**
- 화면코드 = G017
![image](https://user-images.githubusercontent.com/54697115/82759492-d1905900-9e28-11ea-8440-2f795bfe1d34.png)

**화면재현**
- Step1. G017 진입

**ASIS → TOBE**

1. 헤더텍스트 변경
- ASIS = 헤더 텍스트 : 내용
- TOBE = 헤더 텍스트 : 공지사항 상세

2. 상단 Staust bar 색상 변경
- ASIS = 회색
- TOBE = 흰색

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.8
수정

**Comment by younbly** [comment]
수정확인
