### ISSUE TITLE
[FE_046]_댓글에서 프로필 이미지Crop 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#193]
**작성사유**
- 댓글에서 프로필 이미지Crop 에러

**화면**
- 화면코드 = G001/Xa001/Xa002
![image](https://user-images.githubusercontent.com/54697115/82760247-52515400-9e2d-11ea-8de2-17f0a9444ed7.png)

**화면재현**
- Step1. 프로필을 기본 이미지가 아닌 첨부된 이미지로 변경
- Step2. I001 진입
- Step3. 댓글 입력

**ASIS → TOBE**
- ASIS = 프로필의 양옆이 잘려서(Crop)되어 나옴
- TOBE = 프로필 Crop영역 재조정

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
