### ISSUE TITLE
[IMP_013]_댓글/답글에서 "줄바꿈"은 생략

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#195]
**작성사유**
- 댓글/답글에서 줄바꿈 허용여부에 대한 논의필요

**화면**
- 화면코드 = Xa002
![image](https://user-images.githubusercontent.com/54697115/82760586-639b6000-9e2f-11ea-8c4b-11956e80bda5.png)

**화면재현**
- Step1. I001 진입
- Step2. 줄바꿈을 다수 사용한 댓글 입력
- Step2. 댓글페이지로 이동

**ASIS → TOBE**
- ASIS = 줄바꿈 적용
- TOBE = 줄바꿈 생략

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.8 
입려단에서 입력 안되고 댓글 Insert Or Update 로 수정

**Comment by younbly** [comment]
수정확인
