### ISSUE TITLE
[FE_048]_댓글/답글에 300자 이상 입력 예외처리

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#196]
**작성사유**
- 댓글/답글에 300자 이상 입력 예외처리

**화면**
- 화면코드 = Xa003
![image](https://user-images.githubusercontent.com/54697115/82760734-9abe4100-9e30-11ea-8f0b-128c88af3f8f.png)

**화면재현**
- Step1. I001 진입
- Step2. 댓글에 600자 이상 입력
- Step3. 입력 Button Tap

**ASIS → TOBE**
- ASIS = 이벤트 없음
- TOBE = 300자 이상 입력시, 아래 Toast message 표시

    "댓글/답글은 최대 300자까지 입력가능합니다 "

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4 
수정

**Comment by younbly** [comment]
**기능변경 재요청**
- 사유 : Toast message가 여러번 요청되어 사라지지 않고 계속 표시되는 문제가 발생
![image](https://user-images.githubusercontent.com/54697115/83328903-6da2e000-a2c1-11ea-9b1d-1024748ab6fb.png)

**ASIS → TOBE**
- ASIS = 300자 이상 입력시, 아래 Toast message 표시
- TOBE = 300자 이상 초과 입력 후, 등록 Button을 누르면 아래 Toast message 표시

    "댓글/답글은 최대 300자까지 입력가능합니다 "

**Comment by younbly** [comment]
Toast message 제거

**Comment by kimbakcho** [comment]
1.8.8 
수정

**Comment by younbly** [comment]
수정확인
