### ISSUE TITLE
[J002]_디자인 개선(텍스트 줄간격 수정 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#200]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/82771707-d9c3b500-9e77-11ea-8d03-db77bdc6fc1b.png)

**수정요청 :** 
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 배경색상 #F2F0F1(J파트 공통)
2. #454F63 색상 적용 / 텍스트 상하단 간격 16px 적용
3. 텍스트 줄 간격 6px 적용

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 10
앱 버전 = 1.8.1

**Comment by kimbakcho** [comment]
1.8.4 수정
