### ISSUE TITLE
[FE_049]_이슈볼 "주소" 위치에 "제목"이 표시됨

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#209]
**작성사유**
- 이슈볼 "주소" 위치에 "제목"이 표시됨

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/82828644-82136100-9eec-11ea-9fe9-5c53bf95f89f.png)

**화면재현**
- Step1. H001 진입

**ASIS → TOBE**
- ASIS = 주소 표시 영역에 제목이 표시됨
- TOBE = 주소가 표시되도록 변경

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
