### ISSUE TITLE
[논의필요][FE_050]_첨부이미지가 20개일 때, 이슈볼 등록 실패

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#210]
**작성사유**
- 첨부이미지가 20개일 때, 이슈볼 등록 실패

**화면**
- 화면코드 = IM001
![image](https://user-images.githubusercontent.com/54697115/82828878-fbab4f00-9eec-11ea-95a5-ea86fd856abf.png)

**화면재현**
- Step1. 이슈볼 수정하기 진입
- Step2. 첨부이미지 20개 삽입
- Step3. 완료 Button Tap

**ASIS → TOBE**
- ASIS = 로딩 상태에서 변화없음
- TOBE = (논의필요)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
해당 부분 압축 안된 대용량 이미지의 첨부로 인해 서버에서 팅켜낸것으로 추정됨 
1.8.4 이미지 압축 추가 되었으니 이후 1.8.4 에서  재테스트 
현재 10MB 이상 이미지는 서버에서 팅켜내도록 설정 되어 있음. 
압축된 이미지로는 10MB가 넘기 힘겹다고 판단되나 혹시 넘으면 
허용 용량 범위를 키워야됨,

**Comment by younbly** [comment]
수정확인 (1.8.7)
