### ISSUE TITLE
[FE_051]_이슈볼에서 "생성시간"위치에 "남은시간"이 표시됨

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#211]
**작성사유**
- [FE_051]_이슈볼에서 "생성시간"에 "남은시간"이 표시됨

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/82829283-de2ab500-9eed-11ea-8815-b84db1dc9822.png)

**화면재현**
- Step1. H001 진입

**ASIS → TOBE**
- ASIS = 이슈볼에서 "생성시간"위치에 "남은시간"이 표시됨
- TOBE = 생성시간 값 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
