### ISSUE TITLE
[논의필요][FE_052]_GPS off 시, 이슈볼 제작 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#213]
**작성사유**
- GPS off 시, 이슈볼 제작 에러

**화면**
- 화면코드 = H002
![image](https://user-images.githubusercontent.com/54697115/82832380-d8d16880-9ef5-11ea-9815-da9ccc15c9fd.png)

**화면재현**
- Step1. GPS off
- Step1. H002 진입
- Step1. 이슈볼 선택

**ASIS → TOBE**
- ASIS = 이벤트 없음
- TOBE = 논의필요

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
아래 "GPS on" 요청을 생략할 수 있는지 문의드립니다.

![image](https://user-images.githubusercontent.com/54697115/83329210-29184400-a2c3-11ea-8b09-e1f589ab46f3.png)

**Comment by younbly** [comment]
변경없이 이슈종료
