### ISSUE TITLE
[FE_053]_위치 off 시, 뒤로가기 불가

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#214]
**작성사유**
- 위치 off 시, 뒤로가기 불가

**화면**
- 화면코드 = IM000
![image](https://user-images.githubusercontent.com/54697115/82832595-817fc800-9ef6-11ea-9a82-9b1b17004abf.png)

**화면재현**
- Step1. GPS on
- Step2. IM000 진입
- Step3. GPS off
- Step4. 뒤로가기 Tap

**ASIS → TOBE**
- ASIS = 뒤로가지지 않고 위 화면처럼 표시
- TOBE = 뒤로가기

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4 
에서 재시도 필요

**Comment by younbly** [comment]
이상없음 확인 (1.8.7)
