### ISSUE TITLE
[IMP_018]_IM000 지도에서 +,- Button 제거

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#215]
**작성사유**
- IM001 지도에서 +,- Button 제거 필요

**화면**
- 화면코드 = IM000
![image](https://user-images.githubusercontent.com/54697115/82832685-c4da3680-9ef6-11ea-9954-1ace79d5cd94.png)

**화면재현**
- Step1.  IM000 진입

**ASIS → TOBE**
- ASIS = 지도에서 +,- Button 표시
- TOBE = 지도에서 +,- Button 숨김

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
