### ISSUE TITLE
[FE_055]_이슈볼에서 태그 입력시 에러(예외처리 추가)

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#217]
**작성사유**
- 태그입력창에 처음 입력값이 ,(컴마)면, 그 뒤에 "컴마"를 눌러도 태그입력이 되지 않음

**화면**
- 화면코드 = IM001
![image](https://user-images.githubusercontent.com/54697115/82834013-c574cc00-9efa-11ea-829f-9f64c59822d2.png)

**화면재현**
- Step1. IM001 진입
- Step2. 태그 Button tap
- Step3. ","(컴마 입력)
- Step4. 태그 내용입력
- Step5. ","(컴마 입력)

**ASIS → TOBE**
- ASIS = "컴마"를 눌러도 태그입력이 되지 않음
- TOBE = 태그 입력창에 값이 없을 때 ","(컴마 입력)가 입력되면 아래 Toast message 표시

     "태그 내용을 입력해주세요"

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
1.8.10 확인
