### ISSUE TITLE
[FE_056]_IM001 지도에서 +,- Button 제거

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#218]
**작성사유**
- IM001 지도에서 +,- Button 제거 필요

**화면**
- 화면코드 = IM001
![image](https://user-images.githubusercontent.com/54697115/82834162-42a04100-9efb-11ea-8a7b-0f2f7a94c02d.png)

**화면재현**
- Step1. IM001 진입

**ASIS → TOBE**
- ASIS = IM001 지도에서 +,- Button 표시
- TOBE = IM001 지도에서 +,- Button 숨김

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
