### ISSUE TITLE
[FE_057]_IM001 지도에 "Action이벤트" 제거

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#219]
**작성사유**
- IM001 지도에 "Action이벤트" 제거

**화면**
- 화면코드 = IM001
![image](https://user-images.githubusercontent.com/54697115/82834354-d4a84980-9efb-11ea-8532-30f9eede4626.png)

**화면재현**
- Step1. IM001 진입

**ASIS → TOBE**
- TOBE = IM001 지도에서 아래 "Action이벤트" 제거

  1) Double Tap
  2) Flip

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
