### ISSUE TITLE
[FE_058]_IM001 지도 리로드 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#220]
**작성사유**
- IM001 지도 리로드 에러

**화면**
- 화면코드 = IM001
![image](https://user-images.githubusercontent.com/54697115/82834423-09b49c00-9efc-11ea-9b14-6f7ee295f697.png)

**화면재현**
- Step1. IM001 진입
- Step2. 포루투나 App을 포어그라운드 → 백그라운드 상태
- Step3. 포루투나 App을 백그라운드 상태 → 포어그라운드

**ASIS → TOBE**
- ASIS = 위 화면과 같이 지도를 리로드 하지 못함
- TOBE = IM001 지도 정상적으로 지도 리로드

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
