### ISSUE TITLE
[FE_060]_IM001 Youtube 영상 붙여넣기 Button 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#222]
**작성사유**
- IM001 Youtube 영상 붙여넣기 Button 에러

**화면**
- 화면코드 = IM001
![image](https://user-images.githubusercontent.com/54697115/82834728-ea6a3e80-9efc-11ea-9be4-ec4e72d872b0.png)

**화면재현**
- Step1. Youtube URL 복사
- Step2. IM001 진입
- Step3. Youtube 링크 Button Tap

**ASIS → TOBE**
- ASIS = 붙혀넣기 Button 활성화에 1~2초간 시간이 소요
- TOBE = 시간소요 없이 "붙혀넣기 Button" 활성화

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
