### ISSUE TITLE
[DE_015]_IM001에서 첨부된 이미지 표시 개선사항

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#223]
**작성사유**
- IM001에서 첨부된 이미지 표시 개선 필요

**화면**
- 화면코드 = IM001
![image](https://user-images.githubusercontent.com/54697115/82835117-0e7a4f80-9efe-11ea-9373-cb2cef42680b.png)

**화면재현**
- Step1.  IM001 진입

**ASIS → TOBE**
1. 마지막 이미지 잘림
- ASIS = 화면과 같이 마지막 이미지 잘림
- TOBE = (논의필요)

2. 흰색 이미지
- ASIS = 화면과 같이 이미지 경계의 분간이 어려움
- TOBE = (논의필요)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.3

**Comment by kimbakcho** [comment]
1.8.4 
수정 
가로가 360dp로 설정 되어 있었음.
![image](https://user-images.githubusercontent.com/13299104/82905961-8187d280-9f9f-11ea-9ce1-95040c8bf8d4.png)
