### ISSUE TITLE
[H001]_디자인 개선(콘텐츠 영역 수정)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#226]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83002244-c9facb00-a047-11ea-9ef6-d7b8d5b897a4.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H파트_v0.1][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 이슈볼 아이콘 지름 30px, 상단 간격 16px, 좌우측하단 간격 14px
2. 라인 추가(color : #F4F4F6)
3. 주소 텍스트 font size :12px, color : #78849E / 거리 텍스트 font size : 10px, color : #FF4F9A 
4. 이미지 영역 높이 200px
5. 프로필 아이콘 지름 25px / 닉네임 font size : 12px, 등록시간 font size : 10px
6. font size : 14px, color : #454F63
7.숫자 font size : 12px, font weight : bold / 숫자 위치 정렬(아이콘 밑으로 내려가지 않음)

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.5
수정
