### ISSUE TITLE
[H001]_디자인 개선(기본이미지 추가)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#227]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83002894-8ce30880-a048-11ea-95a7-82ecee4e0ac1.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H파트_v0.1][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 기본 이미지 추가(슬랙에 아이콘 첨부)

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.5
수정
