### ISSUE TITLE
[H002]_디자인 개선(배경색상 지정 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#229]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83003587-7be6c700-a049-11ea-8009-10f4099d6e96.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H파트_v0.1][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. H002 bg_color : #F2F0F1
2. 텍스트 font size :  12px, color : #454F63 / padding : 16px

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.5
수정
