### ISSUE TITLE
C003.큐브 설치

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#23]
수정사항 = 큐브목록 Swipe 대신 그 영역에 선택한 큐브가 표시

![image](https://user-images.githubusercontent.com/54697115/68782483-dd7eaf80-067c-11ea-882b-4ff0db2e851e.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/68958556-b2789500-080f-11ea-9bb3-c3e87479bf14.png)

해당 부분 완료
