### ISSUE TITLE
[H005]_디자인 개선(버튼 간격 수정 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#232]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83004590-cddc1c80-a04a-11ea-8dd0-2347d516b404.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H파트_v0.1][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 상단바 bg color : #FFFFFF
2. H005 bg_color : #F2F0F1
3. ‘파워순’ 버튼과 상하단(헤더,콘텐츠) 간격 16px 적용 

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.5
수정
