### ISSUE TITLE
[H007]_디자인 개선(검색바 변경 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#234]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83005334-a174d000-a04b-11ea-84a7-496cffac0b64.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H파트_v0.1][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 검색바와 상하단(상단바,자기위치) 간격 16px 적용 / 투명도 추가 및 텍스트 변경(슬랙에 공유한 [BETA][디자인검수 H파트_v0.1][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고 / H007)
2. 아이콘 크기 변경(25px) / 애니메이션 추가(개발 공수 발생시 적용시점 논의 필요)

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.5
적용
