### ISSUE TITLE
[FE_062]_ID001에서 등록일시 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#235]
**작성사유**
- ID001에서 등록일시 표시 누락

**화면**
- 화면코드 = ID001
![image](https://user-images.githubusercontent.com/54697115/83037895-49ec5980-a077-11ea-8d1a-90506573461c.png)

**화면재현**
- Step1. ID001

**ASIS → TOBE**
- ASIS = 등록일시 누락
- TOBE = 등록일시 표시(수치 표시 = 2. 과거 (지난 시간))

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.5
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
