### ISSUE TITLE
[FE_063]_"이슈볼 수정하기"에서 첨부된 영상 및 태그표시가 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#237]
**작성사유**
- "이슈볼 수정하기"에서 1)첨부된 영상 및 2)태그 입력영역 표시
![image](https://user-images.githubusercontent.com/54697115/83040680-7d7cb300-a07a-11ea-8cf3-24dc6c69f504.png)

**화면**
- 화면코드 = ID001

**화면재현**
- Step1. Youtube 및 태그를 첨부하여 이슈볼 생성
- Step2. 이슈볼 수정하기 Tap

**ASIS → TOBE**
- ASIS = 1)첨부된 영상 및 2)태그 입력영역 표시누락
- TOBE =1)첨부된 영상 및 2)태그 입력영역 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.6 
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
