### ISSUE TITLE
[DE_017]_이슈볼 수정하기페이지의 "헤더 Text" 변경

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#239]
**작성사유**
- 이슈볼 수정하기페이지의 "헤더 Text" 변경
![image](https://user-images.githubusercontent.com/54697115/83041442-71452580-a07b-11ea-8494-71915c10d9cc.png)

**화면**
- 화면코드 = ID001

**화면재현**
- Step1.  ID001 진입
- Step2.  수정하기

**ASIS → TOBE**
1. 헤더 Text
- ASIS = 이슈볼 만들기
- TOBE = 이슈볼 수정하기

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.6
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
