### ISSUE TITLE
QM003.퀘스트 큐브 만들기 Step2. 박스 설치

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#24]
![image](https://user-images.githubusercontent.com/54697115/68781520-42d1a100-067b-11ea-8f72-ee046bd818c2.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/68994396-dc8c8e80-08c5-11ea-8572-0f65dc3750a0.png)

해당 구분 구현 완료
