### ISSUE TITLE
[IMP_019]_이슈볼 제작 완료 후, 화면을 ID001로 이동 

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#240]
**작성사유**
- 이슈볼 제작 완료 후, 화면을 ID001로 이동 

**화면**
- 화면코드 = IM000
![image](https://user-images.githubusercontent.com/54697115/83041751-cb45eb00-a07b-11ea-9b9d-8d3a20a5dce7.png)

**화면재현**
- Step1.  IM000 진입
- Step2.  이슈볼 내용 작성
- Step3.  완료 Button Tap

**ASIS → TOBE**
- ASIS = 이슈볼 제작 완료 후, H001로 이동
- TOBE = 이슈볼 제작 완료 후, 해당 이슈볼의 ID001로 이동 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.6
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
