### ISSUE TITLE
[FE_066]_이슈볼 삭제 Modal 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#241]
**작성사유**
- 이슈볼 삭제 Modal 누락(디자인 작업 누락)

**화면**
- 화면코드 = ID001_1 / ID001_2
![image](https://user-images.githubusercontent.com/54697115/83046693-54602080-a082-11ea-954a-3e938683c687.png)

**화면재현**
- Step1.  ID001 진입
- Step2.  옵션 Button Tap
- Step3.  삭제하기 Button Tap

**ASIS → TOBE**
- ASIS = 이슈볼 삭제
- TOBE = Modal을 띄운 뒤, 삭제하기 Button을 누르면 삭제

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.6
추가

**Comment by younbly** [comment]
수정확인 (1.8.7)
