### ISSUE TITLE
[DE_018]_ID001에서 설치장소 및 기여자의 Text가 짤림

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#242]
**작성사유**
- ID001에서 설치장소 및 기여자의 Text가 짤림

**화면**
- 화면코드 = ID001
![image](https://user-images.githubusercontent.com/54697115/83043888-66d85b00-a07e-11ea-98c2-f4b1ce77e6af.png)

**화면재현**
- Step1.  ID001 진입

**ASIS → TOBE**
- ASIS = ID001에서 설치장소 및 기여자의 Text가 짤림
- TOBE = 짤림이슈 해결

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.6
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
