### ISSUE TITLE
[FE_065]_이슈볼 기여자 수 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#243]
**작성사유**
- 이슈볼 "기여자 수" 에러

**화면**
- 화면코드 = ID001
![image](https://user-images.githubusercontent.com/54697115/83048349-6cd13a80-a084-11ea-84a5-2721a5cd66ee.png)

**화면재현**
- Step1. ID001 진입
- Step2. 상세정보 펼치기 Button tap

**ASIS → TOBE**
- ASIS = 기여자 값이 "Up/Down"를 누른 유저수에 연동되지 않음
- TOBE = 기여자 값이 "Up/Down"를 누른 유저수에 연동

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.4

**Comment by kimbakcho** [comment]
1.8.6
수정

**Comment by younbly** [comment]
수정확인 (1.8.7)
