### ISSUE TITLE
[H001]_디자인 개선(터치영역, 폰트 깨짐 수정 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#244]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83217984-f594c700-a1a7-11ea-998a-842606c4dcf1.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H,,I,ID파트_v0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 태그 터치 영역
2. 주소 폰트 깨짐 수정

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.6

**Comment by kimbakcho** [comment]
1.8.7 수정
