### ISSUE TITLE
[H003_공통]_디자인 개선(그림자 효과 변경)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#245]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83218184-7e136780-a1a8-11ea-9a01-229ddfe66820.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H,,I,ID파트_v0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 그림자 효과(콘텐츠 배경 color : #455B63, 불투명도8% 적용 / x:0, y:4 b: 16)
문서 H003_PLAY활성화 참고

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.6

**Comment by kimbakcho** [comment]
1.8.7
수정
