### ISSUE TITLE
[I001]_디자인 개선(검색바 투명도 적용 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#246]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83218474-ef531a80-a1a8-11ea-9287-1809d4a44279.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H,,I,ID파트_v0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 검색바와 상단바 간격 16px
2. 검색바, 자기 위치로 아이콘 bg투명도 80% 적용

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.5

**Comment by kimbakcho** [comment]
1.8.7
수정
