### ISSUE TITLE
[ID001]_디자인 개선(지도 영역 아이콘 위치 변경)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#247]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83218609-38a36a00-a1a9-11ea-9278-cfe02ccea75a.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H,,I,ID파트_v0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 헤더 하단 지도 영역 h : 244px
이슈볼 아이콘 가운데 정렬(헤더 하단 지도 영역을 기준)

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.5

**Comment by kimbakcho** [comment]
해당 부분 상단 헤더를 투명으로 가져 가게 되면 수정 사항 처럼 중간에 위치 할수가 없음. 
 현재 처럼 사용 하거나 
 위에 상단바를 투명하기 않게 바꾸어야함. 
 둘중 한개를 선택 해주세요 .

![image](https://user-images.githubusercontent.com/13299104/83262653-5350ff80-a1f8-11ea-91bc-aca2cca97183.png)
