### ISSUE TITLE
[ID001]_디자인 개선(헤더에 제목 표시 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#249]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83219046-473e5100-a1aa-11ea-9673-c5c552415c4f.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H,,I,ID파트_v0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 스크롤 업에 따른 제목 표시(제목열이 가려질 때) / 최대 표시 글자 띄어쓰기 포함18자
2. 아이콘 크기 변경 및 수정
3. Tag bg color : #E4E7E8 / boder color : #CCCCCC
4. 댓글 font size : 14px, weight : bold
5. 댓글 페이지로 이동’과 하단 아이콘 간격 16px
6. Bg color : #F5F5F5 / ‘의견을 남겨주세요’ font size : 14px, bg color : #FFFFFF
7. Bg color : #F5F5F5

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.5

**Comment by kimbakcho** [comment]
1.8.7 수정
