### ISSUE TITLE
[ID001]_디자인 개선(영역별 구분선 적용)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#251]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83220119-1b709a80-a1ad-11ea-9304-e4b99dce863d.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 H,,I,ID파트_v0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 구분선 4px 적용(당초 bg 적용, 개발에 쉬운 방식 사용해줄 것) /  color : #E4E7E8

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.5

**Comment by kimbakcho** [comment]
1.8.7
수정
