### ISSUE TITLE
[FE_067]_회원가입 직후, 설정 Button 진입 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#253]
**작성사유**
- 회원가입 직후, 바로 설정 Button을 Tap하면 회색화면이 표시됨

**화면**
- 화면코드 = J007/G001
![image](https://user-images.githubusercontent.com/54697115/83322326-a3c86b80-a291-11ea-8701-b4135e44aabe.png)

**화면재현**
- Step1. 회원가입 완료
- Step2. 바로 표시되는 G001에서 설정 Button Tap

[!] App을 종료하거나, Background로 이동하지 않고 설정 Button을 Tap해야 함

**ASIS → TOBE**
- ASIS = 화면과 같은 회색화면 표시
- TOBE = G009(설정 페이지)로 이동

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8
수정

**Comment by younbly** [comment]
수정확인
