### ISSUE TITLE
[FE_068]_이전 프로필 표시에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#254]
**작성사유**
- 회원가입 시, 뒤로가기를 누르면 이전에 로그인한 프로필이 표시

**화면**
- 화면코드 = J007/G001
![image](https://user-images.githubusercontent.com/54697115/83322485-0ec67200-a293-11ea-9167-800a54839b97.png)

**화면재현**
- Step1. 로그인 상태에서 로그아웃(어떤 계정이든 상관없음)
- Step2. 회원가입 진행
- Step3. 뒤로가기 Tap (안드로이기 기기 Back Button)

**ASIS → TOBE**
- ASIS = 이전에 로그인한 계정의 프로필 화면 표시
- TOBE = App 종료

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8
수정

**Comment by younbly** [comment]
수정확인
