### ISSUE TITLE
[IMP_020]_휴대폰 인증화면에서 "Keypad 옵션"이 다름

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#255]
**화면**
- 화면코드 = J004/J010
![image](https://user-images.githubusercontent.com/54697115/83322601-01f64e00-a294-11ea-8762-97bd4d6f7ed0.png)

**ASIS → TOBE**
- ASIS = 1)휴대폰입력창과 2)인증번호 입력창의 keypad 옵션이 다름
- TOBE = 휴대폰입력창 keypad로 통일

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8
수정
