### ISSUE TITLE
[IMP_021]_태그 순위에서 영향력 삭제

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#256]
**작성사유**
- 태그 순위에서 영향력 삭제를 논의하고자 함
(사유1 : 초기에는 적은 숫자가 표시됨)
(사유2 : 태그파워 값이 유저에게 어떤 영향력이 있을지 고민됨, 
예를 들어 네이버에서도 검색순위가 표시되지 검색량이 표시되지 않음)

**화면**
- 화면코드 = H001 / H006
![image](https://user-images.githubusercontent.com/54697115/82281944-9c6dac00-99cd-11ea-8fe0-dd65d599ed48.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8
수정

**Comment by younbly** [comment]
수정확인
