### ISSUE TITLE
[FE-069]_H008에서 지우기 Button 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#258]
**작성사유**
- H008에서 지우기 Button이 작동하지 않음

[!] 디폴트 상태값에서만 작동하지 않는 듯

**화면**
- 화면코드 =I001 /H008
![image](https://user-images.githubusercontent.com/54697115/83323289-b2665100-a298-11ea-88b2-d897bf9d97ca.png)

**화면재현**
- Step1. H008 진입
- Step2. X Button Tap

**ASIS → TOBE**
- ASIS = 이벤트 없음
- TOBE = 검색어 삭제 기능 작동

[!] 새로 검색어를 입력하면 작동함, 디폴트 상태값에서만 작동하지 않는 듯

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 재시도 요청

**Comment by younbly** [comment]
커서가 근처에 있을때는 Tap이 잘 작동하지 않음

**Comment by kimbakcho** [comment]
1.8.9 터치 영역 확장으로 수정

**Comment by younbly** [comment]
1.8.10 확인
