### ISSUE TITLE
[DE_019]_I001에서 Button 위치 개선필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#259]
**작성사유**
- ID001에서 "검색창"과 "자기위치로 이동Button"이 너무 붙어 있음

**화면**
- 화면코드 = ID001
![image](https://user-images.githubusercontent.com/54697115/83323379-594aed00-a299-11ea-94f9-a070be284a7c.png)

**화면재현**
- Step1.  ID001 진입

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 수정

**Comment by younbly** [comment]
수정확인
