### ISSUE TITLE
QM003_1.퀘스트 큐브 만들기 Step2. 박스 설치(목록 접힙)

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#26]
![image](https://user-images.githubusercontent.com/54697115/68782232-6517ee80-067c-11ea-83e1-50d49cfcb2b5.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/68994413-080f7900-08c6-11ea-8419-f7e1daa7a335.png)

해당 부분 구현 완료
