### ISSUE TITLE
[FE-070]_H005 / H005_1에서 검색창 Tap기능 작동X

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#261]
**작성사유**
- H005 / H005_1에서 검색창 Tap기능이 작동X

**화면**
- 화면코드 =H005 / H005_1
![image](https://user-images.githubusercontent.com/54697115/83323683-5b15b000-a29b-11ea-9503-fd295a712ed0.png)

**화면재현**
- Step1. H005 진입(or H005_1)
- Step2. 검색창 Tap

**ASIS → TOBE**
- ASIS = 이벤트 없음
- TOBE = 입력창 Tap → 이전 페이지로

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8
이전 검색 페이지로 이동하도록 설정

**Comment by younbly** [comment]
수정확인
