### ISSUE TITLE
[FE-071]_H001에서 "중심위치" 검색 기능 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#262]
**작성사유**
- H001에서 "중심위치"를 변경할 경우, '주소없음'으로 표시되는 에러 발생

**화면**
- 화면코드 = H001/H007
![image](https://user-images.githubusercontent.com/54697115/83324129-06276900-a29e-11ea-980a-3e5c5ba36b15.png)

**화면재현**
- Step1. H001 진입
- Step2. 중심위치를 Tap하여 H007로 이동
- Step3. 중심위치를 어떤 장소로 지정(테스트 시에는 '대화역'으로 이동)
- Step4. 다시 H001에서 중심위치를 Tap
- Step5. 검색를 Tap하여 H001로 이동

**ASIS → TOBE**
- ASIS = 주소없음 Text 표시
- TOBE = "주소를 알 수 없습니다" Text 표시 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 수정

**Comment by younbly** [comment]
공백으로 표시됨

**Comment by kimbakcho** [comment]
1.8.9 수정 >> 주소 정보 조합 로직 변경

**Comment by younbly** [comment]
1.8.10 확인
