### ISSUE TITLE
[FE-073]_J010에서 "휴대폰 인증번호" 자동입력 기능 작동X

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#264]
**작성사유**
- GPS off 시, GPS On 중복요청

**화면**
- 화면코드 = J010
![image](https://user-images.githubusercontent.com/54697115/83328506-6af2bb80-a2be-11ea-99a0-46d83523b0c4.png)

**화면재현**
- Step1. J010 진입
- Step2. 인증번호 요청

**ASIS → TOBE**
- ASIS = 인증번호가 인증번호 입력창에 자동 입력되지 않음
- TOBE = 인증번호가 인증번호 입력창에 자동 입력

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 수정

**Comment by younbly** [comment]
수정확인
