### ISSUE TITLE
[I001]_디자인 개선(불투명도 조절)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#267]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83343915-76d09300-a33b-11ea-999b-fb95ea79b2a8.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 불투명도(0%적용) 조절로 숨길 수 있는지?
2. 불투명도 80% 적용

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 2번 방법으로 적용 1번은 어려움
