### ISSUE TITLE
[ID001]_디자인 개선(이슈볼 위치 변경 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#269]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83343970-1f7ef280-a33c-11ea-8fc7-86277f2d07db.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 상단 헤더를 흰색 배경(투명도 제거)으로 고정하고, 이슈볼 아이콘을 지도 중앙에 오도록 변경 요청

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 수정
