### ISSUE TITLE
[persona]_디자인 개선(텍스트 간격 수정 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#274]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83344094-98cb1500-a33d-11ea-9b03-2fa0392208d1.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 닉네임(font size : 17px / weight : Bold), 국가명(font Size : 12 / weight : Bold) 간격 6px
2. Font color : #454F63

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 
수정
