### ISSUE TITLE
[G017]_디자인 개선(라인 추가)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#275]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83344666-fe6ecf80-a344-11ea-989b-8f3a05140d08.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 1px 라인 적용
2. 그림자 효과 제거(상단 수정 이미지에 따르지 않음 / 문서 업데이트 예정)

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 수정
