### ISSUE TITLE
[ID001]_디자인 개선(터치영역 수정)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#276]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83344695-5efe0c80-a345-11ea-91cd-c5bd37f1869d.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 터치영역 수정

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8
 수정
