### ISSUE TITLE
[IMP_024]_답글 정렬방식 변경

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#278]
**작성사유**
- 일반적으로 상단에 있을 수록, 먼저 등록된 답글인데 
현재 포루투나에서는 그 반대로 되어 있어 인지에 혼동을 줄 여지가 있음

**화면**
- 화면코드 = Xa002
![image](https://user-images.githubusercontent.com/54697115/83344940-6f63b680-a348-11ea-817e-521499fd3c28.png)

**화면재현**
- Step1. ID001 진입
- Step2. Xa002 진입

**ASIS → TOBE**
- ASIS = 화면과 같음
- TOBE = 답글의 경우 시간상 먼저 등록된 답글이 상단에 오도록 변경

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8 
수정

**Comment by younbly** [comment]
수정확인
