### ISSUE TITLE
[FE-074]_댓글 숫자 개선 필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#279]
**작성사유**
- 댓글등록 시, 등록한 댓글의 숫자가 반영되지 않음

**화면**
- 화면코드 = Xa002
![image](https://user-images.githubusercontent.com/54697115/83344977-d1bcb700-a348-11ea-93c9-d56feaa1726b.png)

**화면재현**
- Step1. ID001 진입
- Step2. Xa002 진입

**ASIS → TOBE**
- ASIS = 댓글 등록 시, 등록한 댓글의 숫자가 반영되지 않음
- TOBE = 댓글 등록 시, 등록한 댓글의 숫자가 반영

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.7

**Comment by kimbakcho** [comment]
1.8.8
수정

**Comment by younbly** [comment]
수정확인
