### ISSUE TITLE
[ID001]_디자인 개선(이슈볼 위치 페이지 재적용)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#280]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/83345442-15fe8600-a34e-11ea-87e7-67fde09fa8d7.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 지도 영역 터치시 위치 페이지로 이동(개발 공수 기간이 길 경우, 미룰 수 있음)

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.7

**Comment by kimbakcho** [comment]
보류 추후 계발 예정
