### ISSUE TITLE
[ID001_댓글]_디자인 개선(텍스트 변경 등)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#283]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/84634915-6fa9a780-af2d-11ea-8536-ea191676eb51.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합ver0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 아이콘 높이값 13px(사이즈 변경)
2. [답글 보기]로 텍스트 변경
3. Bg 컬러 : #F5F5F5

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.8.2

**Comment by kimbakcho** [comment]
1.8.9 수정

**Comment by hoyoung-yoo** [comment]
[답글 보기] 버튼 클릭시 [답글숨기기] 표시 필요.
