### ISSUE TITLE
[H001]_디자인 개선(상단바 표시 개선)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#285]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/84635272-f494c100-af2d-11ea-9796-5db30fbf3f2f.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합ver0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. H001 이미지 클릭시, 상단바 미노출

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.8.2

**Comment by kimbakcho** [comment]
1.8.9 수정
