### ISSUE TITLE
[persona_beta]_디자인 개선(아이콘 컬러 변경)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#287]
**작성사유 :** 디자인 개선

![image](https://user-images.githubusercontent.com/39005170/84635942-e5fad980-af2e-11ea-9d00-318918b64380.png)

**수정요청 :** 
슬랙에 공유한 [BETA][디자인검수 통합ver0.2][스토리보드]_포루투나App 메뉴리뉴얼_v0.4 참고
(하단의 순번은 상단 이미지에 표시된 순번과 동일)

1. 아이콘 컬러값 #B1B1B1

**작성자 :** 유호영

**[환경]**
기기 = 갤럭시노트 8
OS 버전 = 안드로이드 9
앱 버전 = 1.8.8.2

**Comment by kimbakcho** [comment]
1.8.9 수정
