### ISSUE TITLE
[FE-075]_B파트 → J001(로그인 화면) 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#289]
**작성사유**
- B001 → J001(로그인 화면) 에러 발생

**화면**
- 화면코드 = B001 / J001
![image](https://user-images.githubusercontent.com/54697115/84794472-4114f500-b031-11ea-9434-61af272c3112.png)

**화면재현**
- Step1. 비 로그인 상태
- Step2. B001 선택
- Step3. 메뉴 중 5번째 버튼 선택(J001)

**ASIS → TOBE**
- ASIS = B파트가 로그인 화면을 가림
- TOBE = 로그인 화면이 정상적으로 노출되도록

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.8.2

**Comment by kimbakcho** [comment]
1.8.9 수정

**Comment by younbly** [comment]
1.8.10 확인
