### ISSUE TITLE
[IMP_026]_네트워크 연결 해제시, 네이버 소셜로그인 예외처리 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#292]
**화면**
- 화면코드 = J001
![image](https://user-images.githubusercontent.com/54697115/84852450-d945c500-b097-11ea-872c-7f0e0771737d.png)

**화면재현**
- Step1. 비 로그인 상태
- Step2. 네트워크 연결 X
- Step3. J001 진입
- Step4. 네이버 Button Tap

**ASIS → TOBE**
- ASIS = 화면과 같은 기본 Dialog 표시
- TOBE = (논의필요)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시S10 5G
- OS버전 = 안드로이드 10
- App버전 = 1.8.8.2

**Comment by kimbakcho** [comment]
1.8.9 토스트 메세지로 수정
