### ISSUE TITLE
[FE-001]_GNB2에서 X Button Tap이벤트

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#308]
**작성사유**
- GNB2에서 X Button Tap이벤트를 누르면 "위치를 재확인"

**화면**
- 화면코드 = H001 / GNB2
![image](https://user-images.githubusercontent.com/54697115/109824434-2c8a9280-7c7c-11eb-9633-130225b1f250.png)

**화면재현**
- Step1. H001 진입
- Step2. Ball 설치 Button 탭
- Step3. X Button 탭

**ASIS → TOBE**
- ASIS = 위치정보를 업데이트
- TOBE = 위치정보를 업데이트하지 않고, GNB2에서 이전 화면으로

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11
- App버전 = v201

**Comment by kimbakcho** [comment]
수정
