### ISSUE TITLE
[FE-002]_L002에서 "운영정책 동의" 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#309]
**작성사유**
- L002에서 "운영정책 동의" 누락

**화면**
- 화면코드 = L002
![image](https://user-images.githubusercontent.com/54697115/109827155-d66b1e80-7c7e-11eb-8452-a25ca6b71d4a.png)

**화면재현**
- Step1. L002 진입

**ASIS → TOBE**
- ASIS = "운영정책 동의" 누락
- TOBE = "운영정책 동의" 추가

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by younbly** [comment]
해당 부분은 XD파일에서 누락되어 있습니다. 디자인 단에서 지원 필요합니다.

**Comment by kimbakcho** [comment]
수정 완료
