### ISSUE TITLE
[FE-003]_L002에서 "모든 약관의 동의 활성화 조건" 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#310]
**작성사유**
- L002에서 "모든 약관의 동의 활성화 조건" 오류
- 
**화면**
- 화면코드 = L002
![image](https://user-images.githubusercontent.com/54697115/109827587-34980180-7c7f-11eb-8191-03b5a79ede93.png)

**화면재현**
- Step1. L002 진입
- Step2. 필수동의에 모두 체크

**ASIS → TOBE**
- ASIS = "모든 약관의 동의 체크버튼" 활성화
- TOBE = "모든 약관의 동의 체크버튼" 비활성화

[!] "마케팅 정보 메일 수신 동의(선택)"까지 포함한 모든 동의가 체크되었을 때, "모든 약관의 동의 체크버튼" 활성화되도록

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정 완료
