### ISSUE TITLE
[FE-004]_L002에서 "마케팅 정보 메일 수신 동의(선택)" 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#311]
**작성사유**
- L002에서 "마케팅 정보 메일 수신 동의(선택)" 오류

**화면**
- 화면코드 = L002
![image](https://user-images.githubusercontent.com/54697115/109828966-77a6a480-7c80-11eb-9d61-cc45682548b9.png)

**화면재현**
- Step1. L002 진입
- Step2. "마케팅 정보 메일 수신 동의(선택)" Tap

**ASIS → TOBE**
- ASIS = "서비스 이용약관" 표시
- TOBE = Tap 이벤트 없음

[!] "마케팅 정보 메일 수신 동의(선택)"는 링크가 아니라 단순 Text 입니다. 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정 완료
