### ISSUE TITLE
[FE-005]_L002에서 "위치기반 서비스 이용약관 동의" Text 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#312]
**작성사유**
- L002에서 "위치기반 서비스 이용약관 동의" Text 수정

**화면**
- 화면코드 = L002
![image](https://user-images.githubusercontent.com/54697115/109829698-20550400-7c81-11eb-80bb-8dc1a15f8ad8.png)

**화면재현**
- Step1. L002 진입

**ASIS → TOBE**
- ASIS = 위치기반 서비스 이용약관 동의
- TOBE =위치정보 처리방침

[!] Text 만 수정해주시면 됩니다.

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
