### ISSUE TITLE
[FE-006]_L004에서 "다음" Button 활성화 조건 수정필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#313]
**작성사유**
- L004에서 "다음" Button 활성화 조건 수정필요

**화면**
- 화면코드 = L004
![image](https://user-images.githubusercontent.com/54697115/109831244-96a63600-7c82-11eb-8bc7-66bbabd81850.png)

**화면재현**
- Step1. L004 진입

**ASIS → TOBE**
- ASIS = 설정한 년도가 "(올해 - 20)"과 같거나 크면 활성화
- TOBE =월, 일단위까지 확인하여, 만 14세 이상일 때 활성화

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
재확인 요청드립니다. 
현재설정으로는 만13세일때로 회원가입이 가능합니다.

ex) 07.03.11이 생일인 경우, 만13세임에도 불구하고 가입가능

**Comment by kimbakcho** [comment]
수정
