### ISSUE TITLE
[FE-007]_L004에서 "생년월일" 디폴트값 수정필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#314]
**작성사유**
- L004에서 "생년월일" 디폴트값 수정필요

**화면**
- 화면코드 = L004
![image](https://user-images.githubusercontent.com/54697115/109831735-103e2400-7c83-11eb-99eb-f3bb9e2f9e4f.png)

**화면재현**
- Step1. L004 진입

**ASIS → TOBE**
- ASIS = 3월 9일 기준 생년월일 디폴트값이 20년 3월 9일로 설정됨
- TOBE = 생년월일의 디폴트값이 오늘날짜에서 "-20년"으로

[!] 3월 9일 기준 생년월일의 디폴트값이 20년 3월 4일로 설정되면 됩니다.
[!] 윤달(2월29일)의 경우, 어떻게 예외처리 되는지 확인 요청드립니다.

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
날짜 에서 365*14(year) 를 뺌 
초기값 -14 년으로 수정

**Comment by younbly** [comment]
디폴트값을 아래와 같이 변경가능한지 문의드립니다. 

년도 = 올해 -14
월 = 당월
일 = 당일(Today)

**Comment by kimbakcho** [comment]
수정
