### ISSUE TITLE
[FE-008]_일반 회원가입단계에서 단계를 표시하는 Progress bar 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#315]
**작성사유**
- 일반 회원가입단계에서 단계를 표시하는 Progress bar 오류

**화면**
- 화면코드 = L002/L004/L005
![image](https://user-images.githubusercontent.com/54697115/109832891-27314600-7c84-11eb-8778-08e1010193b9.png)

**화면재현**
- Step1. L002 진입
- Step2. L004 진입
- Step3. L005 진입

**ASIS → TOBE**
- ASIS = L002/L004/L005에서 Progress bar가 총 4칸으로 설정됨
- TOBE = L002/L004/L005에서 Progress bar가 총 5칸으로 설정됨

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
