### ISSUE TITLE
[FE-009]_L005에서 "국가" 디폴트값의 출처

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#316]
**작성사유**
- L005에서 "국가" 디폴트값의 출처 논의필요

**화면**
- 화면코드 = L005
![image](https://user-images.githubusercontent.com/54697115/109835938-05858e00-7c87-11eb-87a7-2d6981247d7f.png)

**화면재현**
- Step1. 설정App에서 디바이스의 언어를 중국어로 설정
- Step2. L005 진입

**ASIS → TOBE**
- ASIS = "국가"의 디폴트값이 "중국"
- TOBE =

**논의항목**
- 국가의 디폴트값이 디바이스의 "언어"가 아니라, "통신사 국가코드"에서 추출 할수는 없는지 확인 요청드립니다.

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정 완료

**Comment by younbly** [comment]
디폴트값이 1)한국으로 고정인지, 2)통신사 국가코드로 설정된 것인지 문의드립니다.

**Comment by kimbakcho** [comment]
통신사의 국가 코드로 변경
