### ISSUE TITLE
[FE-011]_L005에서 "인증번호 유효시간" 변경

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#318]
**작성사유**
- L005에서 "인증번호 유효시간" 변경

**화면**
- 화면코드 = L005
![image](https://user-images.githubusercontent.com/54697115/109837410-8002dd80-7c88-11eb-97c8-bb170ecb7958.png)

**화면재현**
- Step1. L005 진입
- Step2. 인증번호 요청

**ASIS → TOBE**
- ASIS = 인증번호 유효시간이 30분
- TOBE =인증번호 유효시간을 5분으로

[!] 유효시간이 30분에서 5분으로 변경되면, 서버자원을 덜 소모하는지 논의필요

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by younbly** [comment]
[!] 휴대폰 재실행 시, 인증번호요청 대기시간 초기화 되는 이슈 함께 논의 필요

**Comment by kimbakcho** [comment]
수정
