### ISSUE TITLE
[FE-013]_L005에서 유효성검사 메시지 수정 필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#320]
**작성사유**
- L005에서 유효성검사 메시지 수정 필요

**화면**
- 화면코드 = L005
![image](https://user-images.githubusercontent.com/54697115/109983704-6a53ed80-7d46-11eb-987e-ebc2c00cf9f2.png)

**화면재현**
- Step1. L005 진입
- Step2. 인증번호 요청
- Step3. 인증시, 입력한 휴대폰 번호를 수정
- Step4. 다음 Button을 Tap

**ASIS → TOBE**
- ASIS = "don't have authHistory" 유효성검사 메시지 등장
- TOBE = "휴대폰번호를 확인하세요" 유효성검사 메시지 등장

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
아직 수정이 되어 있지 않습니다. 재확인 요청드립니다.

**Comment by kimbakcho** [comment]
수정
