### ISSUE TITLE
[FE-014]_L007에서 "아이디 입력창"의 키패드 수정필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#321]
**작성사유**
- L007에서 "아이디 입력창"의 키패드 수정필요

**화면**
- 화면코드 = L007
![image](https://user-images.githubusercontent.com/54697115/109985960-a4be8a00-7d48-11eb-9f0c-bc468e2ff6ce.png)

**화면재현**
- Step1. L007 진입
- Step2. 아이디 입력창 포커스

**ASIS → TOBE**
- ASIS = 일반 키패드 등장
- TOBE = 이메일 키패드 등장

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
