### ISSUE TITLE
[FE-018]_L008에서 프로필&배경 이미지입력Modal 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#325]
**작성사유**
- L008에서 프로필&배경 이미지입력Modal 오류

**화면**
- 화면코드 = L008
![image](https://user-images.githubusercontent.com/54697115/109994501-b86dee80-7d50-11eb-9db3-c8830bafc90d.png)

**화면재현**
- Step1. L008 진입
- Step2. 프로필 Tap

**ASIS → TOBE**
- ASIS = 화면과 같이 이미지 입력 Modal이 보이지 않음
- TOBE =아래  XD디자인 화면과 같이 Modal이 보이도록 수정

![image](https://user-images.githubusercontent.com/54697115/109994688-e4896f80-7d50-11eb-802e-4f2e22ea413c.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
