### ISSUE TITLE
[FE-020]_L008에서 자기소개 최대입력값 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#327]
**작성사유**
- L008에서 자기소개 최대입력값 수정 필요

**화면**
- 화면코드 = L008
![image](https://user-images.githubusercontent.com/54697115/109996083-3a124c00-7d52-11eb-909b-ee32f51f4276.png)

**화면재현**
- Step1. L008 진입

**ASIS → TOBE**
- ASIS = 자기소개 최대입력값이 80
- TOBE =자기소개 최대입력값이 100

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
