### ISSUE TITLE
[FE-021]_L008에서 다음 Button의 활성화 조건 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#328]
**작성사유**
- L008에서 다음 Button의 활성화 조건 수정

**화면**
- 화면코드 = L008
![image](https://user-images.githubusercontent.com/54697115/109996295-6c23ae00-7d52-11eb-9174-bc3eb8a9d11c.png)

**화면재현**
- Step1. L008 진입
- Step2. 닉네임에 1자 입력

**ASIS → TOBE**
- ASIS = 다음 Button이 변화없이 비활성화 상태
- TOBE =다음 Button이 활성화 상태로 변경

[!] 현재는 닉네임과 자기소개에 모두 데이터를 1자 이상 입력한 상태에서 활성화 됨

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
