### ISSUE TITLE
[FE-026]_휴대폰으로 패스워드 찾기에서 인증번호 유효성검사 메시지 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#334]
**작성사유**
- [FE-026]_휴대폰으로 패스워드 찾기에서 인증번호 유효성검사 메시지 오류

**화면**
- 화면코드 = L014
![image](https://user-images.githubusercontent.com/54697115/110202557-cb95d100-7eac-11eb-94b7-b1873d59bb7e.png)

**화면재현**
- Step1. L014 진입
- Step2. 계정에 저장된 휴대폰번호와 다른 번호를 입력
- Step3. 인증번호 요청

**ASIS → TOBE**
- ASIS = 화면과 같이 마지막 Text가 .... 처리됨
- TOBE = 아래와 같이 Text 수정

아이디에 저장된 휴대폰번호와 일치하지 않습니다.
번호변경 시, 이메일 인증으로 패스워드를 변경해주세요.

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
재확인 요청드립니다.

**ASIS** 
휴대폰으로 패스워드 찾기에서 인증번호 유효성검사 메시지 오류

**TOBE** 
아이디에 저장된 휴대폰번호와 일치하지 않습니다. 
번호변경 시, 이메일 인증으로 패스워드를 변경해주세요.

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
현재(ASIS)
![image](https://user-images.githubusercontent.com/54697115/111067917-cfa79b80-8509-11eb-8c39-4982ef759287.png)

TOBE
아이디에 저장된 휴대폰번호와 일치하지 않습니다.
번호변경 시, 이메일 인증으로 패스워드를 변경해주세요.

**Comment by younbly** [comment]
TOBE
아이디에 저장된 휴대폰 번호와 일치하지 않습니다.
번호 변경시, 이메일 인증으로 비밀번호를 변경 해주세요.

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
수정미확인, 다음 배포버전에서 확인해야하는지?
