### ISSUE TITLE
[FE-027]_휴대폰으로 패스워드 찾기에서 인증번호 요청오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#335]
**작성사유**
- 휴대폰으로 패스워드 찾기에서 인증번호 요청오류

**화면**
- 화면코드 = L014
![image](https://user-images.githubusercontent.com/54697115/110202605-3941fd00-7ead-11eb-881e-df0c39da241a.png)

**화면재현**
- Step1. L014 진입
- Step2. 계정에 저장된 휴대폰번호와 다른 번호를 입력
- Step3. 인증번호 요청
- Step4. 다시 계정에 저장된 휴대폰번호 입력
- Step5. 인증번호 요청

**ASIS → TOBE**
- ASIS = 응답없음
- TOBE = 인증번호 요청 기능 작동

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
작동 유무 확인 재 테스트
