### ISSUE TITLE
[FE-029]_약관동의 페이지에서 "다음" Button 활성화 조건 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#337]
**작성사유**
- 약관동의 페이지에서 "다음" Button 활성화 조건 오류

**화면**
- 화면코드 = L002
![image](https://user-images.githubusercontent.com/54697115/110235674-cb610880-7f74-11eb-8332-a76ac6356a64.png)

**화면재현**
- Step1. L002 진입
- Step2. 필수약관에 모두 동의

**ASIS → TOBE**
- ASIS = 다음 Button 활성화되지 않음
- TOBE = 다음 Button 활성화

[!] L002에서 다음 Button의 활성화 조건은 모든 약관에 동의가 아니라, 필수약관에만 동의하면 활성화 됩니다.

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
