### ISSUE TITLE
[FE-034]_L017에서 이메일에서 받은 인증번호 재설정 링크 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#343]
**작성사유**
- 이메일에서 받은 인증번호 재설정 링크 오류

**화면**
- 화면코드 = L017
![image](https://user-images.githubusercontent.com/54697115/110244367-c1a1ca00-7fa1-11eb-92e0-4b229f18c223.png)

**화면재현**
- Step1. 비밀번호 재설정 이메일 요청
- Step2. 메일에 첨부된 링크를 클릭

**ASIS → TOBE**
- ASIS = 404 오류 발생
- TOBE = 비밀번호 재설정 페이지로 연결

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
