### ISSUE TITLE
[진행대기][논의필요][FE-035]_H001에서 메뉴Button 기능임시 변경

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#344]
**작성사유**
- H001에서 메뉴Button 기능임시 변경

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/110244499-4e4c8800-7fa2-11eb-8095-7a9f363b7293.png)

**화면재현**
- Step1. H001 진입

**ASIS → TOBE**
- ASIS = 
- TOBE = 1)Swipe 기능 삭제, 2)Tap 기능 변경 (메뉴 펼침 → Contents list 이동)

[!]미개발 영역인 3)Favorite list, 4)Follower's list 숨기기 위한 조치임

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
해당 부분 화면의 복잡도로 소스 코드 결합도가 높아 수정이 어려움 Swipe 기능 삭제 할시 버그 다수 발생 가능성이 큼

**Comment by younbly** [comment]
기능을 단순 페이지 이동으로 "임시 대체"
