### ISSUE TITLE
[FE-036]_H001에서 Ball컨텐츠에서 기본프로필 이미지 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#345]
**작성사유**
- H001에서 Ball컨텐츠에서 기본프로필 이미지 누락

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/110244761-adf76300-7fa3-11eb-82e2-2fdf5efbe794.png)

**화면재현**
- Step1. H001 진입

**ASIS → TOBE**
- ASIS = Ball컨텐츠에서 유저의 "기본 프로필"이 누락됨
- TOBE = 유저의 프로필이 기본프로필일 경우, 기본 프로필 이미지를 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
