### ISSUE TITLE
[FE-037]_H001에서 Ball컨텐츠에서 거리Data 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#346]
**작성사유**
- H001에서 Ball컨텐츠에서 기본프로필 이미지 누락

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/110244845-03cc0b00-7fa4-11eb-933f-e61f478373fc.png)

**화면재현**
- Step1. H001 진입

**ASIS → TOBE**
- ASIS = Ball컨텐츠에서 유저의 "기본 프로필"이 누락됨
- TOBE = 유저의 프로필이 기본프로필일 경우, 기본 프로필 이미지를 표시

[!] 디바이스의 위치값이 확인 되지 않았을 때, 표시하지 못하는게 아닌가 추측

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
