### ISSUE TITLE
[FE-038]_H001에서 Tag가 없으면 Tag 영역 공백 발생

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#347]
**작성사유**
- H001에서 Tag가 없으면 Tag 영역 공백 발생

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/110244903-47267980-7fa4-11eb-82c2-22501b4516ec.png)

**화면재현**
- Step1. (Tag가 없는 상태) H001 진입

**ASIS → TOBE**
- ASIS = Tag영역 공백
- TOBE = Tag가 없으면, 해당 영역의 공백을 생략하도록 예외처리

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
