### ISSUE TITLE
[진행대기][논의필요][FE-040]_위치정보 Permission 이슈

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#349]
**작성사유**
- 위치정보 Permission 이슈

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/110327970-0c811780-805e-11eb-81ee-a389555afad2.png)

**화면재현**
- Step1. App 첫 실행하여 H001 진입

**ASIS → TOBE**
- ASIS = 위치정보 Permission을 항상 허용해야 H001정상작동
- TOBE = 

[!] "이번만 허용"을 했을 때도 되지 않는 이슈
[!] 더 나은 UX경험상, 아래 Flow 차트대로 진행할 수 없는지?

![image](https://user-images.githubusercontent.com/54697115/110327907-f2473980-805d-11eb-8e6e-0349e62f9098.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by younbly** [comment]
진행예정
디자인에서 화면디자인 필요 = 목요일 지원예정

**Comment by kimbakcho** [comment]
app 테스트 결과 영구 불허를 인지할수가 없음. 
최대한 가능한 정도에서 구현함. 
Z005 페이지의 내용은 Z004에 넣어 줘야함. 
Z004 에서 app 셋팅으로 넘어 갈수 있음.
단 영구 불허시 프로그램 코드상에서 알수 없지만 
위치 정보 접근 동의 누를시 아무 반응이 없음. 
반응 없을시 또는 영구 거부 시 app 셋팅 버튼을 눌러 허가권 변경을 으로 유도하도록 해야함.
