### ISSUE TITLE
QM009.퀘스트 큐브 만들기 Step3. 큐브 세부설정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#35]
![image](https://user-images.githubusercontent.com/54697115/68782122-2eda6f00-067c-11ea-9f49-b4cb99932f88.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/68994473-b74c5000-08c6-11ea-90b1-2854f8a64f83.png)

3,4 는 고도화 부분에서 
일단 일정에서 제외 하기로함
