### ISSUE TITLE
[FE-041]_H001에서 "중심위치" 로딩중일때 Tap 이벤트 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#350]
**작성사유**
- H001에서 "중심위치" 로딩중일때 Tap 이벤트 오류

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/110328274-7ef1f780-805e-11eb-8233-2ebd1fea3678.png)

**화면재현**
- Step1. H001 진입
- Step2. "중심위치" 로딩중일 때  Tap

**ASIS → TOBE**
- ASIS = 회색화면으로 이동
- TOBE = "위치 확인중입니다" 토스트메시지 띄움

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
