### ISSUE TITLE
[FE-044]_Ball 조회수가 카운트 되지 않음

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#353]
**작성사유**
- Ball 조회수가 카운트 되지 않음

**화면**
- 화면코드 = H001/ID01_001
![image](https://user-images.githubusercontent.com/54697115/110333918-85d03880-8065-11eb-9393-787071ef4eb1.png)

**화면재현**
- Step1. H001 진입
- Step2. 아무 Ball을 선택하여, ID01_001로 진입

**ASIS → TOBE**
- ASIS = 조회수 0에서 변화없음(카운트 되지 않음)
- TOBE = Ball 상세페이지에 들어갈때마다 조회수 1씩 증가

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
