### ISSUE TITLE
[FE-045]_H001에서 일부 Ball의 "거리값"이 누락됨

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#354]
**작성사유**
- H001에서 일부 Ball의 "거리값"이 누락됨

**화면**
- 화면코드 = H001/ID01_001
![image](https://user-images.githubusercontent.com/54697115/110334597-4c4bfd00-8066-11eb-8d9f-1f80bf7efe36.png)

**화면재현**
- Step1. H001 진입

[!] 위 이미지 Ball 제목 = 리모델링 축하

**ASIS → TOBE**
- ASIS = H001에서 일부 Ball의 거리값이 누락됨
- TOBE =H001에서 일부 Ball의 거리값 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
