### ISSUE TITLE
[FE-046]_H001에서 기본 프로필 표시되지 않음

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#355]
**작성사유**
- H001에서 Ball제작자의 프로필이 기본 프로필이면 표시되지 않음

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/110335229-f88de380-8066-11eb-849e-4d20c5e5bd4a.png)

**화면재현**
- Step1. H001 진입
- Step2. 제작자 프로필이 기본프로필인 Ball을 발견

[!] 위 이미지 Ball 제목 = 브걸 응원합니다:))))

**ASIS → TOBE**
- ASIS =  기본 프로필 표시되지 않음
- TOBE = 기본 프로필 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
