### ISSUE TITLE
[FE-046]_H001에서 Ball의 등록일시 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#356]
**작성사유**
- H001에서 Ball의 등록일시 누락(대신에 남은 Live시간이 표시됨)
 
**화면**
- 화면코드 = H001/ID01_001
![image](https://user-images.githubusercontent.com/54697115/110336203-f9734500-8067-11eb-9c3e-56a641416bcb.png)

**화면재현**
- Step1. H001 진입

**ASIS → TOBE**
- ASIS =  H001에서 Ball의 남은 Live시간이 표시됨
- TOBE = 남은 Live시간 대신 등록일시 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
