### ISSUE TITLE
[FE-047]_ID01_001에서 "등록일자" Text 삭제

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#357]
**작성사유**
- ID01_001에서 "등록일자" Text 삭제
 
**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/110336571-54a53780-8068-11eb-95d7-d699abae9e61.png)

**화면재현**
- Step1. ID01_001

**ASIS → TOBE**
- ASIS =  "등록일자" Text 표시
- TOBE = "등록일자" Text 제거

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
