### ISSUE TITLE
[FE-049]_ID01_001에서 상세정보 영역에 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#359]
**작성사유**
- ID01_001에서 상세정보 영역에 오류
  
**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/110341751-08f58c80-806e-11eb-8596-680cb64761e0.png)

**화면재현**
- Step1. 로그인상태에서 H001 진입
- Step2. 사전에 제작된 Ball중 하나를 삭제
- Step3. 사전에 제작된 다른 Ball의 상세페이지(ID01_001)에 진입

**ASIS → TOBE**
- ASIS =  화면과 같이 회색영역 표시됨
- TOBE = 정상적으로 상세페이지 출력

[!] 특정 Ball을 지울 때, 다른 Ball에도 영향을 끼치는 것으로 추측됨

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
