### ISSUE TITLE
QD001.퀘스트 큐브 상세페이지(상세정보)

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#36]
![image](https://user-images.githubusercontent.com/54697115/69115544-45455800-0acc-11ea-9420-44a614afdd6f.png)

![image](https://user-images.githubusercontent.com/54697115/69115535-3b235980-0acc-11ea-9246-5030416c6a35.png)

![image](https://user-images.githubusercontent.com/54697115/69115563-51311a00-0acc-11ea-9ff7-82d81114f331.png)

![image](https://user-images.githubusercontent.com/54697115/69115567-57bf9180-0acc-11ea-8a13-9fca17b3b06e.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/69903833-4175d780-13e2-11ea-91ba-8876f2ab72f1.png)

해당 부분 완료
