### ISSUE TITLE
[FE-050]_H001에서 Ball "수정하기"기능 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#360]
**작성사유**
- H001에서 Ball "수정", "삭제"기능 오류
  
**화면**
- 화면코드 = H001_2
![image](https://user-images.githubusercontent.com/54697115/110342407-b668a000-806e-11eb-8cbe-3e9965cb0a4f.png)

**화면재현**
- Step1. 로그인상태에서 H001 진입
- Step2. 제작한 Ball의 옵션Button을 눌러 H001_2 진입
- Step3. 수정 Button을 Tap

**ASIS → TOBE**
- ASIS =  반응 없음
- TOBE = 수정 페이지로 이동

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
