### ISSUE TITLE
[FE-051]_H001에서 Ball "삭제하기"기능 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#361]
**작성사유**
- H001에서 Ball "삭제하기"기능 오류
  
**화면**
- 화면코드 = H001_2
![image](https://user-images.githubusercontent.com/54697115/110342551-df893080-806e-11eb-90cc-66e03091fcdd.png)

**화면재현**
- Step1. 로그인상태에서 H001 진입
- Step2. 제작한 Ball의 옵션Button을 눌러 H001_2 진입
- Step3. 삭제하기 Button을 Tap

**ASIS → TOBE**
- ASIS =  반응 없음
- TOBE = Ball 삭제Modal 띄움

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
