### ISSUE TITLE
[FE-053]_Ball 수정 시, 지도이동 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#363]
**작성사유**
- Ball 수정 시, 지도이동 오류
  
**화면**
- 화면코드 = H001_2/IM01_001
![image](https://user-images.githubusercontent.com/54697115/110343828-39d6c100-8070-11eb-9de5-877124461e07.png)

**화면재현**
- Step1. 로그인 상태에서 자신이 제작한 Ball 상세페이지(IM01_001)로 이동
- Step2. 수정하기 Button을 Tap

**ASIS → TOBE**
- ASIS =  IM01_001로 진입한 후, Ball 설치위치에서 "현재 내 위치"로 지도이동
- TOBE = Ball 설치 위치에서 지도이동 없음

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
