### ISSUE TITLE
[FE-055]_H001에서 타인의 Ball "공유하기"기능에 토스트메시지 추가

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#365]
**작성사유**
- H001에서 타인의 Ball "공유하기"기능에 토스트메시지 추가
  
**화면**
- 화면코드 = H001_1
![image](https://user-images.githubusercontent.com/54697115/110345667-2debfe80-8072-11eb-93bb-b849d4344df8.png)

**화면재현**
- Step1. 로그인상태에서 H001 진입
- Step2. 다른 유저가 제작한 Ball의 옵션Button을 눌러 H001_1 진입
- Step3. 공유하기 Button을 Tap

**ASIS → TOBE**
- ASIS =  반응 없음
- TOBE = "준비중 입니다" Toast message 띄움 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
