### ISSUE TITLE
[FE-056]_G001에서 Ball 안에 기본프로필 이미지 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#366]
**작성사유**
-G001에서 Ball 안에 기본프로필 이미지 누락
  
**화면**
- 화면코드 = G001
![image](https://user-images.githubusercontent.com/54697115/110346399-d9954e80-8072-11eb-98dd-a17f45336eb9.png)

**화면재현**
- Step1. 기본프로필로 설정된 계정을 준비
- Step2. 로그인 후 Ball을 1개 이상제작
- Step3. G001 진입
- Step4. 제작된 Ball 리스트를 확인

**ASIS → TOBE**
- ASIS =  Ball 안에 기본 프로필 이미지 누락
- TOBE = 누락된 기본 프로필 이미지 표시

[!] G001에서 Ball 내에 "프로필 이미지"가 늦게(5초 이상....) 로딩되는데 로딩속도를 개선할 수 있는지 문의드립니다.

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
