### ISSUE TITLE
D001_1.PLAY(목록형) – 퀘스트큐브

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#37]
![image](https://user-images.githubusercontent.com/54697115/69115409-bfc1a800-0acb-11ea-9ea7-923640649209.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/69903851-708c4900-13e2-11ea-8a3e-5dc56685ebd2.png)

해당 부분 구현 완료
