### ISSUE TITLE
[FE-060]_IM01_001에서 지도오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#370]
**작성사유**
-IM01_001에서 지도오류
  
**화면**
- 화면코드 = IM01_001
![image](https://user-images.githubusercontent.com/54697115/110354073-1d8c5180-807b-11eb-8039-310bf03814fa.png)

**화면재현**
- Step1. IM01_001로 이동
- Step2. App을 Background 상태로
- Step3. App을 다시 Forekground 상태로

**ASIS → TOBE**
- ASIS =  화면과 같이 지도 호출 실패
- TOBE = 지도가 표시되도록

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
