### ISSUE TITLE
[FE-060]_I001에서 "재검색 Button" 기능 수정필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#373]
**작성사유**
- I001에서 "재검색 Button" 기능 수정필요
  
**화면**
- 화면코드 = I001
![image](https://user-images.githubusercontent.com/54697115/110357523-b8d2f600-807e-11eb-9589-a2474730c87f.png)

**화면재현**
- Step1. I001로 이동
- Step2. 지도 이동

**ASIS → TOBE**
- ASIS =  Tap이벤트 → 1)표시된 지도영역에 설치된 Ball을 검색, 2) 지도배율을 Default 값으로
- TOBE = "2)지도배율을 Default 값으로" 삭제

[!] 문제점 = 지도배율이 줄면서, Swipe 했을 때 밖에 있는 Ball은 지도상에서 표시되지 않음

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by younbly** [comment]
검색 후 "지도배율을 Default 값으로" 기능을 삭제하는 것으로 결정

**Comment by kimbakcho** [comment]
수정
