### ISSUE TITLE
[FE-064]_Ball상세페이지에서 Tag 표시 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#377]
**작성사유**
- Ball상세페이지에서 Tag 표시 누락
  
**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/110360650-567bf480-8082-11eb-9f96-edc695f944a8.png)

**화면재현**
- Step1. Tag가 입력된 Ball 상세페이지로 이동

**ASIS → TOBE**
- ASIS =  상세정보에서 Tag 누락
- TOBE = 입력한 Tag 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
