### ISSUE TITLE
[FE-067]_Ball 상세페이지에서 지도오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#379]
**작성사유**
- Ball 상세페이지에서 지도오류
  
**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/110361412-4dd7ee00-8083-11eb-8af1-8ca44edff09c.png)

**화면재현**
- Step1. Ball 상세페이지로 이동
- Step2. App을 Background 상태로
- Step3. App을 다시 Forekground 상태로

**ASIS → TOBE**
- ASIS =  화면과 같이 지도 호출 실패
- TOBE = 지도가 표시되도록

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
