### ISSUE TITLE
D004_1.PLAY(지도형) – 퀘스트큐브

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#38]
![image](https://user-images.githubusercontent.com/54697115/69115454-f26ba080-0acb-11ea-8644-fc934cc6fa06.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/69903857-8732a000-13e2-11ea-9705-6f98c9cf4ff2.png)

해당 부분 구현 완료
