### ISSUE TITLE
[FE-069]_Ball 제작 시, Youtube 첨부 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#382]
**작성사유**
- Ball 제작 시, Youtube 첨부 오류
  
**화면**
- 화면코드 = ID01_001/IM01_001
![image](https://user-images.githubusercontent.com/54697115/110362849-2a15a780-8085-11eb-8e62-98188ee5fed3.png)

**화면재현**
- Step1. Ball 제작페이지로 이동
- Step2. Youtube를 입력
- Step3. 완료 Button을 Tap하여 제작완료

**ASIS → TOBE**
- ASIS =  상세페이지에 youtube 누락
- TOBE = 상세페이지에 youtube 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
