### ISSUE TITLE
[FE-070]_Ball 제작 완료 후, 해당 Ball 상세페이지로 이동필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#383]
**작성사유**
- Ball 제작 완료 후, 해당 Ball 상세페이지로 이동필요
  
**화면**
- 화면코드 = IM01_001
![image](https://user-images.githubusercontent.com/54697115/110363104-7cef5f00-8085-11eb-9c6e-f42e2f818276.png)

**화면재현**
- Step1. Ball 제작페이지로 이동
- Step2. 완료 Button을 Tap하여 제작완료

**ASIS → TOBE**
- ASIS =  H001로 이동
- TOBE = 해당 Ball의 상세페이지로 이동

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
