### ISSUE TITLE
[FE-071]_Ball 제작시, Tag에 특수문자 제한 필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#384]
**작성사유**
-Ball 제작시, Tag에 특수문자 제한 필요
  
**화면**
- 화면코드 = IM01_004_02
![image](https://user-images.githubusercontent.com/54697115/110363598-1caced00-8086-11eb-8bf9-94b32414f4e9.png)

**화면재현**
- Step1. IM01_004_02로 이동
- Step2.태그에 특수문자 입력

**ASIS → TOBE**
- ASIS =  특수문자 입력됨
- TOBE = "특수문자는 입력이 불가능합니다" Toast message 띄움

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
적용 하지만 모든 문자에 대해서 제외 적용은 불가능 자주 쓰이는 특수문자만 제거 
토스트 메세지 뛰우는것은 공수가 들어가서 간단히 입력 불가능으로 처리
