### ISSUE TITLE
[FE-073]_Tag에 컴마(,)입력 시, 태그를 생성

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#386]
**작성사유**
-Tag에 컴마(,)입력 시, 태그를 완료
  
**화면**
- 화면코드 = IM01_004_02
![image](https://user-images.githubusercontent.com/54697115/110363598-1caced00-8086-11eb-8bf9-94b32414f4e9.png)

**화면재현**
- Step1. IM01_004_02로 이동
- Step2.태그에 Text를 입력
- Step3.컴마(,)를 입력

**ASIS → TOBE**
- ASIS =  컴마(,) 입력됨
- TOBE = Tag를 생성

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
