### ISSUE TITLE
[FE-074]_Ball수정 시, 상세페이지에서 지도오류1

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#387]
**작성사유**
-Ball 상세페이지에서 지도오류1
  
**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/110361412-4dd7ee00-8083-11eb-8af1-8ca44edff09c.png)

**화면재현**
- Step1. ID01_001로 이동
- Step2. Ball 수정

**ASIS → TOBE**
- ASIS =  컴마(,) 입력됨
- TOBE = Tag를 생성

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
