### ISSUE TITLE
[FE-076]_로그아웃 후 처리 오류1

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#389]
**작성사유**
- 로그아웃 후, H001에서 Ball에 대한 수정/삭제 권한 존재

**화면**
- 화면코드 = G009 / H001
![image](https://user-images.githubusercontent.com/54697115/110507277-352f0d00-8143-11eb-9fe9-ae2c6c32f723.png)

**화면재현**
- Step1. 로그아웃
- Step2. 로그아웃한 계정으로 제작한 Ball의 옵션 Button을 Tap

**ASIS → TOBE**
- ASIS = tap이벤트 없음
- TOBE = L001 로그인 페이지 띄움

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
