### ISSUE TITLE
[FE-077]_Ball상세페이지의 옵션Button 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#390]
**작성사유**
- 비로그인 상태에서 Ball상세페이지의 옵션Button 오류

**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/110508560-7673ec80-8144-11eb-8c79-7cea256c1e1e.png)

**화면재현**
- Step1. 비로그인 상태
- Step2. Ball 상세페이지로 이동
- Step3. 옵션 Button을 Tap

**ASIS → TOBE**
- ASIS =  반응 없음
- TOBE = L001(로그인 페이지 띄움)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
