### ISSUE TITLE
[FE-078]_Ball상세페이지의 유저 표시 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#391]
**작성사유**
- 비로그인 상태에서 Ball상세페이지의 지도에서 "플레이어" 표시

**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/110508667-95727e80-8144-11eb-9331-9217518dbe1c.png)

**화면재현**
- Step1. 비로그인 상태
- Step2. Ball 상세페이지로 이동

**ASIS → TOBE**
- ASIS =  지도에 유저의 위치가 회색 원으로 표시
- TOBE = 프로필 디폴트 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
