### ISSUE TITLE
[FE-086]_K001_03에서 필터오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#398]
**작성사유**
- K001_03에서 필터 중, "가까운 거리순" 오류
 
**화면**
- 화면코드 = K001_03
![image](https://user-images.githubusercontent.com/54697115/110513826-010b1a80-814a-11eb-8152-78efe586f94c.png)

**ASIS → TOBE**
- ASIS = 가까운 거리순으로 정렬되지 않음
- TOBE = 가까운 거리순으로 정렬 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
