### ISSUE TITLE
QD001_2.퀘스트 큐브 상세페이지(참가자)

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#40]
![image](https://user-images.githubusercontent.com/54697115/69115629-93f2f200-0acc-11ea-9ded-6c86df4a1bcb.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/69903867-a2051480-13e2-11ea-900a-ae244d55e677.png)

구현 완료
