### ISSUE TITLE
[DE-01]_Z001 화면 교체

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#400]
작성사유

Z001 화면 교체 필요

> 화면

![image](https://user-images.githubusercontent.com/39005170/110736708-7c1a2100-826f-11eb-8c87-7850fba34dbc.png)

> 화면코드 = Z001

> 수정요청
  

- (1) 페이지 교체
   - 로고 가운데 정렬
   - 하단 텍스트 (Noto Sans CJK KR / 12px / Medium / #7A7A7A)
 
> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.32 / FORUTONA_APP_통합아이콘

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
