### ISSUE TITLE
[DE-03]_H001 화면 수정(2)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#402]
작성사유

H001 디자인 수정 필요

> 화면

![image](https://user-images.githubusercontent.com/39005170/110738156-209d6280-8272-11eb-8a2a-321755c224c9.png)

> 화면코드 = H001 / GNB

> 수정요청
  
(1) H001 헤더 버튼 영역
  - 아이콘 교체(통합 아이콘 참조)
  - 아이콘 기준 상하 마진값 10px 적용

(2) 구분선
 -  구분선 추가(#E4E7E8 / 1px)

(3) GNB 영역
 - 아이콘 교체 / 텍스트 추가 (통합 아이콘 참조)
 - 아이콘 기준 상하 마진값 10px 적용
 - 영역 그림자 효과(#2F3035 / x : 0 , y : 3, b : 6)

 

> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.32 / FORUTONA_APP_통합아이콘

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
1. 현재 펼짐 기능 없음. 
수정
