### ISSUE TITLE
[FE-088]_G001에서 메뉴Button 예외처리

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#403]
**작성사유**
-GH001에서 메뉴Button 기능 임시변경

**화면**
- 화면코드 = G001
![image](https://user-images.githubusercontent.com/54697115/110816764-faf27680-82ce-11eb-8d62-b93e9eb56965.png)

**화면재현**
- Step1. 로그인 상태
- Step2. G001 진입

**ASIS → TOBE**
- ASIS = 
- TOBE = 1)Swipe 기능 삭제, 2)Tap 이벤트없음

[!]미개발 영역인 Wallet 페이지를 숨기기 위한 조치임

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by younbly** [comment]
1차결정 = 1)Swipe 기능 숨김, 2)Tap 이벤트없음

대안 = "준비중화면" 입니다.

**Comment by kimbakcho** [comment]
수정
