### ISSUE TITLE
[FE-089]_G001에서 자기소개 Empty message 예외처리

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#404]
**작성사유**
- G001에서 자기소개 Empty message 예외처리

**화면**
- 화면코드 = G001

**화면재현**
- Step1. (자기소개가 없는 계정으로) 로그인
- Step2. G001 진입

**ASIS → TOBE**
- ASIS = 아래 기능 누락
![image](https://user-images.githubusercontent.com/54697115/110821659-a271a800-82d3-11eb-9fc2-8816be115b43.png)

- TOBE = 스토리보드 참조하여 기능 추가 
![image](https://user-images.githubusercontent.com/54697115/110821535-853cd980-82d3-11eb-937d-86f4de56c2f2.png)

[!] 베타기간 적용여부 논의 필요

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
