### ISSUE TITLE
[논의필요][FE-090]_G001에서 "팔로워, 팔로잉, U레벨 영역" 임시 숨김처리

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#405]
**작성사유**
-GH001에서 G001에서 "팔로워, 팔로잉, U레벨 영역" 임시 숨김처리

**화면**
- 화면코드 = G001
![image](https://user-images.githubusercontent.com/54697115/110822888-df8a6a00-82d4-11eb-895a-dc21f4352432.png)

**화면재현**
- Step1. 로그인 상태
- Step2. G001 진입

**ASIS → TOBE**
- ASIS = 
- TOBE = 팔로워, 팔로잉, U레벨 영역 임시 숨김

[!] 미개발 영역인 소셜, U레벨 기능을 숨기기 위한 조치
[!] 해당영역을 숨길 시, 디자인을 어떻게 구성하지 논의 필요

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
