### ISSUE TITLE
[FE-091]_계정수정시 "성별" 수정 되지 않음

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#406]
**작성사유**
- 계정수정에서 "성별" 수정 되지 않음

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/110825243-3002c700-82d7-11eb-8bc7-8416040a3b0c.png)

**화면재현**
- Step1. 로그인 상태
- Step2. G010 진입
- Step3. 성별 변경

**ASIS → TOBE**
- ASIS = 성별 변경사항 저장되지 않음
- TOBE = 성별 변경사항 저장

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
