### ISSUE TITLE
[FE-092]_계정수정에서 닉네임 수정 시, 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#407]
**작성사유**
- 계정수정에서 닉네임 수정 시, 오류

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/110826107-18780e00-82d8-11eb-95fb-1612f6dcc762.png)

**화면재현**
- Step1. 로그인 상태
- Step2. G010 진입
- Step3. 닉네임 수정
- Step4. 완료 Button을 Tap

**ASIS → TOBE**
- ASIS = 수정 시, Loading 상태에서 변화 없음
- TOBE = 오류수정

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
