### ISSUE TITLE
[FE-093]_계정수정에서 닉네임, 자기소개 글제한

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#408]
**작성사유**
- 계정수정에서 닉네임, 자기소개 글제한 방식에 대한 논의 필요

**화면**
- 화면코드 = G010
![image](https://user-images.githubusercontent.com/54697115/110827313-490c7780-82d9-11eb-8174-0f2efdfeb67e.png)

**화면재현**
- Step1. 로그인 상태
- Step2. G010 진입
- Step3. 닉네임 or 자기소개에 제한된 글자 수보다 많은 글자 입력

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by younbly** [comment]
수정

**Comment by kimbakcho** [comment]
수정
