### ISSUE TITLE
[FE-095]_G009에서 미개발된 메뉴 Tap이벤트 예외처리

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#410]
**작성사유**
- G009에서 미개발된 메뉴 Tap이벤트 예외처리

**화면**
- 화면코드 = G009
![image](https://user-images.githubusercontent.com/54697115/110830382-80c8ee80-82dc-11eb-88f9-6d5a48f85c78.png)

**화면재현**
- Step1. 로그인 상태
- Step2. G009 진입
- Step3. 미개발 메뉴(공개범위, 알림, 버전정보)를 Tap

**ASIS → TOBE**
- ASIS = Tap이벤트 없음
- TOBE = "준비중입니다" Toast message 띄움

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
