### ISSUE TITLE
[FE-098]_H001에서 Redusized1(이미지가 없는 Ball)에서 위치/거리 값이 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#413]
**작성사유**
- H001에서 Redusized1(이미지가 없는 Ball)에서 위치/거리 값이 누락

**화면**
- 화면코드 = H001
![image](https://user-images.githubusercontent.com/54697115/111069400-434ca700-8510-11eb-9c38-6ce19810e4a5.png)

**화면재현**
- Step1. H001 진입
- Step2. 이미지가 첨부되지 않은 Ball 확인

**ASIS → TOBE**
- ASIS = 위치/거리 값이 누락
- TOBE = 위치/거리 값을 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
