### ISSUE TITLE
[FE-100]_로그아웃 후, 다른 계정으로 로그인 시 에러

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#415]
**작성사유**
- 로그아웃 후, 다른 계정으로 로그인 시 에러
  
**화면**
- 화면코드 = G001
![image](https://user-images.githubusercontent.com/54697115/111072023-27e79900-851c-11eb-98f9-dd415156c122.png)

**화면재현**
- Step1. A계정으로 로그인
- Step2. 로그아웃
- Step3. B계정으로 로그인
- Step4. G001로 이동

**ASIS → TOBE**
- ASIS =  (로그아웃 한) A계정의 프로필 표시
- TOBE = 현재 계정인 B계정 프로필 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
