### ISSUE TITLE
[FE-101]_댓글/답글에서 기본프로필 이미지 누락 

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#416]
**작성사유**
- 댓글/답글에서 기본프로필 이미지 누락

**화면**
- 화면코드 = Xa01_001
![image](https://user-images.githubusercontent.com/54697115/111072542-59616400-851e-11eb-97fc-773003677a38.png)

**화면재현**
- Step1. 프로필이 기본으로 설정되어 있는 계정으로 로그인
- Step2. 댓글/답글 입력

**ASIS → TOBE**
- ASIS =  댓글/답글에서 "기본 프로필 이미지" 누락
- TOBE = "기본 프로필 이미지" 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
