### ISSUE TITLE
[FE-103]_댓글 입력란에서, 기본프로필 이미지 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#418]
**작성사유**
- 댓글 입력란에서, 기본프로필 이미지 누락

**화면**
- 화면코드 = Xa01_001
![image](https://user-images.githubusercontent.com/54697115/111072725-25d30980-851f-11eb-9f73-44e2f21c9f95.png)

**화면재현**
- Step1. 프로필이 기본으로 설정되어 있는 계정으로 로그인
- Step2. Ball 상세페이지로 이동

**ASIS → TOBE**
- ASIS =  댓글 입력화면에서 "기본 프로필 이미지" 누락
- TOBE = "기본 프로필 이미지" 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
