### ISSUE TITLE
[FE-104]_신고하기 기능 오류1

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#419]
**작성사유**
- 신고하기 > 기타 선택시, 오류

**화면**
- 화면코드 = Xc01_001
![image](https://user-images.githubusercontent.com/54697115/111072984-4bacde00-8520-11eb-8bd7-2019c0502e1b.png)

**화면재현**
- Step1. 로그인
- Step2. Ball 신고하기
- Step3. 기타 선택

**ASIS → TOBE**
- ASIS =  검은색 화면으로 이동
- TOBE = "기타"항목으로 신고하기

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
