### ISSUE TITLE
[FE-106]_댓글/답글 삭제하기 기능 수정필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#421]
**작성사유**
- 댓글/답글 삭제하기 기능 수정필요

**화면**
- 화면코드 = Xc01_001
![image](https://user-images.githubusercontent.com/54697115/111073771-65035980-8523-11eb-888c-c62edc7f0415.png)

**화면재현**
- Step1. 로그인
- Step2. 자신이 제작한 Ball을 삭제

**ASIS → TOBE**
- ASIS =  위 화면과 같이 "삭제됨" 메시지 외 데이터 표시 없음
- TOBE = 
     1) 댓글/답글메시지 → 삭제된 메시지입니다
     2) 옵션버튼을 숨김
     3) 프로필, 닉네임, 등록일시는 숨기지 않고 그대로 표시

#참고
![image](https://user-images.githubusercontent.com/54697115/111073408-e0640b80-8521-11eb-80a9-cb74c773e413.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
Text 수정요청
ASIS = 삭제됨
TOBE = 삭제된 메시지 입니다

**Comment by kimbakcho** [comment]
수정
