### ISSUE TITLE
[FE-109]_IM01_001의 지도에서 +-Button 숨김[FE-109]_IM01_001의 지도에서 +-Button 숨김

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#424]
**작성사유**
- IM01_001의 지도에서 +-Button 숨김[FE-109]_IM01_001의 지도에서 +-Button 숨김

**화면**
- 화면코드 = IM01_001
![image](https://user-images.githubusercontent.com/54697115/111075703-9fbdbf80-852c-11eb-90eb-8b91d0683e67.png)

**화면재현**
- Step1. 로그인
- Step2. IM01_001로 이동

**ASIS → TOBE**
- ASIS =   +-Button 표시
- TOBE =  +-Button 숨김

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
