### ISSUE TITLE
[FE-111]_IM01_001에서 위치검색창의 디폴트 입력값 논의필요

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#426]
**작성사유**
- IM01_001에서 위치검색창의 디폴트 입력값 논의필요

**화면**
- 화면코드 = IM01_001
![image](https://user-images.githubusercontent.com/54697115/111076047-02fc2180-852e-11eb-9002-f6af858b531b.png)

**화면재현**
- Step1. 로그인
- Step2. IM01_001로 이동

**ASIS → TOBE**
- ASIS =  검색입력 필드에 "현재유저의 주소"가 표시
- TOBE = "주소 검색"으로 Text 변경
 
**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
