### ISSUE TITLE
[FE-112]_IM01_001에서 주소정보 예외처리

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#427]
**작성사유**
- IM01_001에서 주소정보 예외처리

**화면**
- 화면코드 = IM01_001
![image](https://user-images.githubusercontent.com/54697115/111076130-68e8a900-852e-11eb-8e58-bb4b576107a9.png)

**화면재현**
- Step1. 로그인
- Step2. IM01_001로 이동
- Step3. 주소정보가 없는 위치로 이동 ex)바다 한가운데

**ASIS → TOBE**
- ASIS = 마지막 주소정보를 표시 
- TOBE = 주소정보가 없을  경우, "주소정보 없음" 등의 메시지를 표시하는 등 예외처리 표시

[!] 가장 문제는 다음 Button을 누르면, 그 주소정보를 가지고 Ball을 제작함

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
