### ISSUE TITLE
[FE-113]_이슈볼 제작 시, 1)제목 및 2)내용의 최대글자 수 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#428]
**작성사유**
- 이슈볼 제작 시, 1)제목 및 2)내용의 최대글자 수 수정

**화면**
- 화면코드 = IM01_004
![image](https://user-images.githubusercontent.com/54697115/111076266-fcba7500-852e-11eb-8b34-c5620d2f8ab8.png)

**화면재현**
- Step1. 로그인
- Step2. IM01_004로 이동

**ASIS → TOBE**

1. 제목
- ASIS = 최대 20자
- TOBE = 최대 50자

2. 내용
- ASIS = 최대 2000자
- TOBE = 최대 2500자

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정

**Comment by younbly** [comment]
![image](https://user-images.githubusercontent.com/54697115/111858662-f63c5b00-897d-11eb-9b97-f0af6859d686.png)

여기 글자수 카운터도 50으로 변경해주세요~

**Comment by kimbakcho** [comment]
수정
