### ISSUE TITLE
[FE-115]_Ball상세페이지에서 "후원하기" 기능 임시 예외처리

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#430]
**작성사유**
- Ball상세페이지에서 "후원하기" 기능 임시 예외처리

**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/111181470-5edbae80-85f1-11eb-8510-05a15e3cbe15.png)

**화면재현**
- Step1. Ball상세페이지로 이동
- Step2. 후원하기 Button을 Tap

**ASIS → TOBE**
- ASIS = 반응 없음
- TOBE = "준비중입니다" Toast message 띄움

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
