### ISSUE TITLE
[FE-117]_Ball상세페이지에서 "Ball영향력 상세영역" 숨김

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#432]
**작성사유**
- Ball상세페이지에서 "Ball영향력 상세영역" 숨김

**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/111181930-cd207100-85f1-11eb-9408-4d0b5a4e251d.png)

**화면재현**
- Step1. Ball상세페이지로 이동

**ASIS → TOBE**
- ASIS = Ball 상세영역 페이지 표시
- TOBE = Ball 상세영역 페이지 숨김

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
