### ISSUE TITLE
[진행대기][논의필요][FE-119]_영향력 Ticket의 디폴트값을 1로 설정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#434]
**작성사유**
- 유저의 영향력 Ticket의 디폴트값을 1로 설정

**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/111184400-48832200-85f4-11eb-92f1-1b8a1a7ae135.png)

**화면재현**
- Step1. 로그인 상태
- Step2. Ball상세페이지로 이동

**ASIS → TOBE**
- ASIS = 영향력 Ticket의 디폴트값이 0으로 설정
- TOBE = 영향력 Ticket의 디폴트값이 1로 설정

[!] 유저의 "영향력 레벨"에 따라서, Ticket의 숫자가 변동되는 기능 구현여부 확인 필요

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
회원 가입시 최초 1로 설정됨.
