### ISSUE TITLE
[FE-120]_영향력 Ticket이 0장일대, 예외처리 누락1

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#435]
**작성사유**
- 영향력 Ticket이 0장일대, 예외처리 누락1

**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/111184742-9d269d00-85f4-11eb-899d-d4a8e9e9729d.png)

**화면재현**
- Step1. 로그인 상태
- Step2. Ball상세페이지로 이동

**ASIS → TOBE**
- ASIS = 화면과 같음
- TOBE = 영향력 Ticket이 0장일때 아래처럼 1) 쿨타임 표시, 2)Tap이벤트 없음 처리

![image](https://user-images.githubusercontent.com/54697115/111185783-b2e89200-85f5-11eb-82a7-3442ac632394.png)

[!] 쿨타임이 지나면 1장 회복
[!] 쿨타임은 1장당 1시간
[!] 유저의 "영향력 레벨"에 따라서, Ticket의 숫자가 변동되는 기능 구현여부 확인 필요

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
