### ISSUE TITLE
[FE-121]_영향력 Ticket의 0장일때 예외처리 누락2

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#436]
**작성사유**
- 영향력 Ticket이 0장일대, 예외처리 누락2

**화면**
- 화면코드 = ID01_002
![image](https://user-images.githubusercontent.com/54697115/111186604-82552800-85f6-11eb-8dbf-22dfae7c027d.png)

**화면재현**
- Step1. 로그인 상태 & 사용가능한 티켓1장 이상
- Step2. Ball상세페이지로 이동
- Step3. 영향력행사 페이지로 이동
- Step4. Ticket을 모두 사용
- Step5. 사용가능한 영향력이 0일 때, 영향력 Button을 Tap

**ASIS → TOBE**
- ASIS = 이벤트 없음
- TOBE = "영향력이 부족합니다" Toast message 띄움
 
**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
