### ISSUE TITLE
[FE-122]_영향력 행사 Button "Tap이벤트" 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#437]
**작성사유**
- 영향력 행사 Button "Tap이벤트" 오류

**화면**
- 화면코드 = ID01_002

**화면재현**
- Step1. 로그인 상태 & 사용가능한 티켓1장 이상
- Step2. Ball상세페이지로 이동
- Step3. 영향력행사 페이지로 이동
- Step4. 비활성화된 "영향력 행사 Button"을 탭

**ASIS → TOBE**
- ASIS = ID001_003으로 이동(아래 화면 참고)
- TOBE = 비활성화된 상태에서는 Tap이벤트 없음
 ![image](https://user-images.githubusercontent.com/54697115/111187000-eb3ca000-85f6-11eb-9b5e-849e473be228.png)

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
