### ISSUE TITLE
[FE-123]_ID01_004에서 "자기위치로 지도이동 Button" 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#438]
**작성사유**
- ID01_004에서 "자기위치로 지도이동 Button" 누락

**화면**
- 화면코드 = ID01_004
![image](https://user-images.githubusercontent.com/54697115/111187517-6900ab80-85f7-11eb-8ad6-b02bc8ee42b8.png)

**화면재현**
- Step1. ID01_004로 이동

**ASIS → TOBE**
- ASIS =  "자기위치로 지도이동 Button" 누락
- TOBE = "자기위치로 지도이동 Button" 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
