### ISSUE TITLE
[FE-125]_ID01_001에서 "댓글 입력영역" 누락

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#440]
**작성사유**
- ID01_001에서 "댓글 입력영역" 누락

**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/111188981-f55f9e00-85f8-11eb-8d45-45e3d436c51e.png)

**화면재현**
- Step1. 이미지 4장이상, Youtube를 첨부하여 Ball 제작
- Step2. 해당 Ball의 상세페이지로 이동

**ASIS → TOBE**
- ASIS =  댓글 입력영역이 누락
- TOBE = 댓글 입력영역이 표시

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
