### ISSUE TITLE
[FE-126]_G001에서 "삭제된 Ball" 정의추가

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#441]
**작성사유**
- G001에서 "삭제된 Ball" 정의추가

**화면**
- 화면코드 = G001
![image](https://user-images.githubusercontent.com/54697115/111191362-54261700-85fb-11eb-8dec-0ab06922629b.png)

**화면재현**
- Step1. 로그인
- Step2. 삭제된 Ball 준비
- Step3. G001에서 진입

**ASIS → TOBE**
- ASIS = 삭제된Ball이 종료된 Ball로 처리
- TOBE = G001의 Ball 히스토리에서 숨김 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
