### ISSUE TITLE
[FE-132]_Ball 수정시 지도위치이동 오류

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#448]
**작성사유**
- Ball 수정시 지도위치이동 오류

**화면**
- 화면코드 = IM01_004_01
![image](https://user-images.githubusercontent.com/54697115/111873002-88218380-89d1-11eb-8061-a196d69fe313.png)

**화면재현**
- Step1. Ball 수정페이지 진입

**ASIS → TOBE**
- ASIS =  Ball 설치위치에서 내 위치로 지도이동
- TOBE = 지도위치 이동없음 

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
