### ISSUE TITLE
[FE-133]_Ball 삭제 시, 히스토리에서 즉시 수정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#449]
**작성사유**
- Ball 삭제 시, 히스토리에서 즉시 수정

**화면**
- 화면코드 = ID01_001
![image](https://user-images.githubusercontent.com/54697115/111873145-3f1dff00-89d2-11eb-9bd4-2f4dd8075807.png)

**화면재현**
- Step1. 신규회원가입
- Step2. Ball 상세페이지 진입

**ASIS → TOBE**
- ASIS =  회색 화면 보이는 오류
- TOBE = 오류 해결

[!] 신규 가입 시, 입력하는 데이터 일부가 누락됨

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
