### ISSUE TITLE
[FE-134]_검은 화면 출력

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#450]
**작성사유**
- 로그인 시 검은 화면 출력

**화면**
- 화면코드 = L001
![image](https://user-images.githubusercontent.com/54697115/112510747-12ecee80-8dd5-11eb-9b49-7f20787f0415.png)

**화면재현**
- Step1. 로그인

**ASIS → TOBE**
- ASIS =  검은 화면 출력
- TOBE = 오류해결

[!] App을 완전히 종료한 뒤, 재실행하면 로그인된 상태로 실행됨

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정

**Comment by kimbakcho** [comment]
모두 수정

**Comment by younbly** [comment]
#추가 발견된 검은화면 리스트
1. 휴대폰으로 패스워드 변경 완료 후
2. I001에서 지도에서 "이 지역 다시 검색" 후
