### ISSUE TITLE
[FE-135]_Ball 제작 시, 계속 로딩상태에 머뭄

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#451]
**작성사유**
- Ball 제작 시, 계속 로딩상태에 머뭄

**화면**
- 화면코드 = IM01_004
![image](https://user-images.githubusercontent.com/54697115/112511165-7f67ed80-8dd5-11eb-8ef5-d3e321c38ea7.png)

**화면재현**
- Step1. IM01_004
- Step2. 제목에 이모티콘 문자를 입력
- Step3. 내용을 입력하고 Ball을 등록

**ASIS → TOBE**
- ASIS =  로딩이 종료되지 않음
- TOBE = Ball 정상적으로 등록

[!] 제목에 이모티콘 문자를 입력한 것이 오류의 원인으로 추측됨

**작성자**
- 전윤민

**환경**
- 기기 = 갤럭시10 5G
- OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
