### ISSUE TITLE
[DE-04]_H001 터치영역 수정

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#452]
작성사유

H001 이슈볼 터치영역 변경

> 화면

![image](https://user-images.githubusercontent.com/39005170/112722799-dc3ae380-8f4e-11eb-9013-2a02ce2306ed.png)

> 화면코드 = H001 / GNB

> 수정요청
  
(1) 터치영역 변경(상세페이지로 이동)

(2) 시간 표시 영역, 배경색 흰색 지정

(3) 태그 없을 시, 상하간격 16px 적용

 

> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.33 / FORUTONA_APP_통합아이콘

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
