### ISSUE TITLE
[DE-05]_H001 터치영역 표시 방식

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#453]
작성사유

H001 디자인 수정 필요

> 화면

![image](https://user-images.githubusercontent.com/39005170/112722903-4d7a9680-8f4f-11eb-866d-bb8ad88cdf0d.png)

> 화면코드 = H001

> 수정요청
  
(1)   터치시 표시 방식

 

> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.33 / FORUTONA_APP_통합아이콘

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
