### ISSUE TITLE
[DE-11]_G011 화면 수정(2)

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#459]
작성사유

G011 디자인 수정 필요

> 화면

![image](https://user-images.githubusercontent.com/39005170/112723392-8fa4d780-8f51-11eb-9495-98a329ee6fdf.png)

> 화면코드 = G011

> 수정요청
  
(1) 
- 아이콘 상하간격 10px 적용
- 시간 표시 영역, 배경색 흰색 지정

(2) 
- 상하간격 16px 적용
- 아이콘 컬러값(#3A3E3F)

> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.33 / FORUTONA_APP_통합아이콘

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
