### ISSUE TITLE
QA002.관리자모드 Drawer

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#46]
![image](https://user-images.githubusercontent.com/54697115/69115831-74a89480-0acd-11ea-8782-69b7b63a4e24.png)

**Comment by younbly** [comment]
UI 변경사항이 있습니다. 작업을 우선 진행하지 말아주세요

**Comment by kimbakcho** [comment]
> UI 변경사항이 있습니다. 작업을 우선 진행하지 말아주세요

확인

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70142619-070b8380-16dd-11ea-868d-d9d9c89a921b.png)

해당 0.5 Ver

![image](https://user-images.githubusercontent.com/13299104/70142599-f529e080-16dc-11ea-9cfe-e1d62307c346.png)

스토리 보드 0.5 버전으로 업데이트 된것으로 프로그램 개발
