### ISSUE TITLE
QA003.관리자모드(인증샷 완료요청)

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#47]
![image](https://user-images.githubusercontent.com/54697115/69115850-82f6b080-0acd-11ea-98b1-1632ea099b67.png)

![image](https://user-images.githubusercontent.com/54697115/69115861-8d18af00-0acd-11ea-9b4c-c1e1a63ae669.png)

**Comment by younbly** [comment]
UI 변경사항이 있습니다. 작업을 우선 진행하지 말아주세요

**Comment by kimbakcho** [comment]
> UI 변경사항이 있습니다. 작업을 우선 진행하지 말아주세요

확인

**Comment by kimbakcho** [comment]
해당 부분은 Play 완료 요청 이후에 개발

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70446105-fb0a3200-1adf-11ea-83da-b086ef366dc7.png)
 해당 부분 개발

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70534754-0bcdad00-1b9f-11ea-95f7-d6c5da95877b.png)

![image](https://user-images.githubusercontent.com/13299104/70534763-112af780-1b9f-11ea-8db8-249782d4bda0.png)

![image](https://user-images.githubusercontent.com/13299104/70534777-1a1bc900-1b9f-11ea-86fa-6a6f28f089df.png)

![image](https://user-images.githubusercontent.com/13299104/70534789-21db6d80-1b9f-11ea-98dd-5bfb8eb84632.png)

완료
