### ISSUE TITLE
[DE]_K001_ 필터 화면 수정

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#497]
작성사유

K001_필터 디자인 수정 필요

> 화면

![image](https://user-images.githubusercontent.com/39005170/113466178-a75ded80-9474-11eb-871e-628b00166d8a.png)

> 화면코드 = K001_필터

> 수정요청
  
(1) 
-  그림자 효과 제거

---------------------------------------------------------------------------

> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.33 / 디자인검수_아이콘셋2

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
