### ISSUE TITLE
[검토요청] [DE]_IM01_ 화면 수정

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#501]
작성사유

태그 입력시 입력된 태그 확인하기 어려움

> 화면

![image](https://user-images.githubusercontent.com/39005170/113470148-4c38f480-948e-11eb-9d24-04a73068864e.png)

> 화면코드 = IM01

> 수정요청
  
(1) 
- 입력된 태그 노출 위치 변경

---------------------------------------------------------------------------

> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.33 / 디자인검수_아이콘셋2

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
