### ISSUE TITLE
[DE]_G001_I001_디자인 수정

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#509]
작성사유

G001, I001 디자인 수정 필요

> 화면

![image](https://user-images.githubusercontent.com/39005170/113499862-5fae9300-9554-11eb-9351-41c6dcae00b0.png)

> 화면코드 = G001, I001

> 수정요청
  
(1) 
- 영향력 아이콘 변경 요청(Influence_I001, 색상 : #F841D9)

---------------------------------------------------------------------------

> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.33 / 디자인검수_아이콘셋

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
