### ISSUE TITLE
[DE]_ID01_디자인 수정

### ISSUE THREAD

**Issue by hoyoung-yoo** [kimbakcho/forutonafront#510]
작성사유

ID01 디자인 수정 필요

> 화면

![image](https://user-images.githubusercontent.com/39005170/113501865-4f51e480-9563-11eb-9ecb-192b62ab9b76.png)

> 화면코드 = ID01

> 수정요청
  
(1) 
- PP → BP 텍스트 수정
 BP, 팔로워 사이 띄어쓰기 적용 요청

---------------------------------------------------------------------------

> 참조문서
 - [FORUTONA]통합_디자인 리뉴얼_ver1.33 / 디자인검수_아이콘셋

> 작성자
  - 유호영

> 환경

기기 = 갤럭시20
OS버전 = 안드로이드 11

**Comment by kimbakcho** [comment]
수정
