### ISSUE TITLE
QA007.퀘스트 실패(시간초과) Dialog

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#57]
![image](https://user-images.githubusercontent.com/54697115/69116140-98200f00-0ace-11ea-96ad-170fe6971d3f.png)

**Comment by younbly** [comment]
해당 페이지는 변경사항이 있습니다. 작업을 우선 순위에서 뒤로 부탁드립니다.

**Comment by kimbakcho** [comment]
> 해당 페이지는 변경사항이 있습니다. 작업을 우선 순위에서 뒤로 부탁드립니다.

확인

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70142844-8600bc00-16dd-11ea-8ee7-6a447a0a512e.png)

삭제된 페이지
