### ISSUE TITLE
QP006.플레이모드 설정

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#64]
![image](https://user-images.githubusercontent.com/54697115/69116399-9efb5180-0acf-11ea-8a77-14c380d4bb2f.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70370539-b29a1b00-190b-11ea-878c-ce24a7ec9535.png)

고도화화로 빠짐
