### ISSUE TITLE
QP006_01.퀘스트 포기 Dialog

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#66]
![image](https://user-images.githubusercontent.com/54697115/69116427-c4885b00-0acf-11ea-811a-9c43d323cf0c.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70370549-c5145480-190b-11ea-9b0f-e65749bc2dcf.png)

고도화로 빠짐
