### ISSUE TITLE
QP010.플레이모드(인증샷 완료요청)

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#76]
![image](https://user-images.githubusercontent.com/54697115/69116836-1087cf80-0ad1-11ea-8e3f-f5c850bdbf26.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70621211-68db6880-1c5c-11ea-8db0-bfd395c8d094.png)

Close
