### ISSUE TITLE
QP010_2.인증샷 실패 Dialog

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#78]
![image](https://user-images.githubusercontent.com/54697115/69116911-49c03f80-0ad1-11ea-99c1-e3831b487506.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70621285-945e5300-1c5c-11ea-884f-20eb3b3f0c7e.png)
Close
