### ISSUE TITLE
QR001.퀘스트결과(플레이어 성적)

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#84]
![image](https://user-images.githubusercontent.com/54697115/70857809-d88d7400-1f38-11ea-9025-34a71884a3f1.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/70914594-a4f73a80-205b-11ea-8335-308a8a3aea63.png)

해당 부분 Close
