### ISSUE TITLE
D001_2.PLAY(목록형) – 이슈큐브

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#88]
![image](https://user-images.githubusercontent.com/54697115/71317628-a3000200-24c7-11ea-848c-ba1d3fb5c79f.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/71584972-48664600-2b58-11ea-8493-f89739e09545.png)
디자자인전 필요한 데이터 만 가져다 놓음
