### ISSUE TITLE
D004_2.PLAY(지도형) – 이슈큐브

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#89]
![image](https://user-images.githubusercontent.com/54697115/71317625-97144000-24c7-11ea-8e1b-f48b8d579b05.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/71521249-40fa2f00-2903-11ea-81ab-0fc24e56c2b0.png)
