### ISSUE TITLE
ID001.이슈큐브 상세페이지

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#91]
![image](https://user-images.githubusercontent.com/54697115/71317639-d347a080-24c7-11ea-9ccc-7fb0340e23fa.png)

![image](https://user-images.githubusercontent.com/54697115/71317642-e35f8000-24c7-11ea-8ed7-37f2aec42f0b.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/71521224-27f17e00-2903-11ea-87e1-55f00bf9f206.png)
