### ISSUE TITLE
IR001.이슈큐브 결과페이지

### ISSUE THREAD

**Issue by younbly** [kimbakcho/forutonafront#93]
![image](https://user-images.githubusercontent.com/54697115/71317673-4ea95200-24c8-11ea-9c55-4ec8d72be426.png)

**Comment by kimbakcho** [comment]
![image](https://user-images.githubusercontent.com/13299104/71586598-25d72b80-2b5e-11ea-876e-940cff9c0567.png)

필요한한 데이터만 가져다 놓은 디자인은 나중에
